import {calculate} from './table-engine';
import type {Config} from './model';
export function accessibleConfig(config:Config,plan:'free'|'plus'|'pro'|'admin'='free'):Config{
 if(plan==='admin')return config;
 const level={free:0,plus:1,pro:2},allowed=(access?:string)=>level[plan]>=level[(access||'free') as 'free'|'plus'|'pro'];
 const effective=Object.fromEntries(Object.entries(config.home.blocks).map(([id,b])=>[id,b.access||'free']));for(let pass=0;pass<100;pass++){let changed=false;for(const [id,b] of Object.entries(config.home.blocks))for(const link of [{children:b.children,access:effective[id]},...b.attachments.map(a=>({children:a.children,access:level[(a.access||'free') as 'free'|'plus'|'pro']>level[effective[id] as 'free'|'plus'|'pro']?a.access!:effective[id]}))])for(const child of link.children||[]){if(effective[child]!==undefined&&level[effective[child] as 'free'|'plus'|'pro']<level[link.access as 'free'|'plus'|'pro']){effective[child]=link.access;changed=true}}if(!changed)break}
 const entries=Object.entries(config.home.blocks).map(([id,b])=>[id,{...b,access:effective[id] as 'free'|'plus'|'pro'}] as const),denied=entries.filter(([,b])=>!allowed(b.access)),open=entries.filter(([,b])=>allowed(b.access));
 const protectedAttachments=entries.flatMap(([,b])=>b.attachments.filter(a=>!allowed(b.access)||!allowed(a.access))),ids=new Set(protectedAttachments.map(a=>a.datasetId)),publicIds=new Set(open.flatMap(([,b])=>b.attachments.filter(a=>allowed(a.access)).map(a=>a.datasetId)));for(const id of publicIds)ids.delete(id);
 const news=new Set(denied.flatMap(([,b])=>b.newsIds||[]));for(const [,b] of open)for(const id of b.newsIds||[])news.delete(id);
 const blocks=Object.fromEntries(entries.map(([id,b])=>[id,allowed(b.access)?{...b,locked:false,attachments:b.attachments.map(a=>({...a,locked:!allowed(a.access),body:allowed(a.access)?a.body:'',title:config.datasets.find(s=>s.id===a.datasetId)?.title||a.title}))}:{...b,locked:true,body:'',attachments:b.attachments.map(a=>({...a,body:'',locked:true,access:b.access})),newsIds:[],photos:[],rankingTheme:undefined}]));
 for(const id of ids){const s=config.datasets.find(s=>s.id===id);if(s?.visible)blocks['dataset:'+id]={...blocks['dataset:'+id],title:s.title,body:'',attachments:[],access:protectedAttachments.find(a=>a.datasetId===id)?.access||denied.find(([,b])=>b.attachments.some(a=>a.datasetId===id))?.[1].access||'plus',locked:true}}
 return {...config,datasets:config.datasets.map(s=>ids.has(s.id)?{...s,limit:2,columns:s.columns.map(c=>({...c,formula:''})),rows:calculate(s).slice(0,2).map(r=>r.map(c=>c.error?'':String(c.value))),note:'공개 미리보기 · 처음 2행',metadata:undefined}:s),stories:config.stories.filter(s=>!news.has(s.id)),ranking:{...config.ranking,rules:config.ranking.rules.filter(r=>!ids.has(r.datasetId))},home:{...config.home,blocks}};
}
