import {z} from 'zod';
export const ChatRequestSchema=z.object({messages:z.array(z.object({role:z.enum(['user','assistant']),content:z.string().trim().min(1).max(4000)})).min(1).max(24),context:z.object({datasetIds:z.array(z.string().max(100)).max(5)}).optional()}).refine(v=>v.messages.reduce((n,m)=>n+m.content.length,0)<=20000,'대화 문맥이 너무 깁니다.').refine(v=>v.messages.at(-1)?.role==='user','마지막 메시지는 질문이어야 합니다.');
export const ChatSourceSchema=z.object({datasetId:z.string().max(100),title:z.string().max(150),note:z.string().max(1500),summary:z.string().max(1500),columns:z.array(z.object({name:z.string().max(100),unit:z.string().max(30)})).max(26),rows:z.array(z.array(z.string().max(500)).max(26)).max(10)});
export const ChatReplySchema=z.object({provider:z.enum(['data','openai']),answer:z.string().min(1).max(12000),sources:z.array(ChatSourceSchema).max(5),context:z.object({datasetIds:z.array(z.string().max(100)).max(5)})});
export type ChatRequest=z.infer<typeof ChatRequestSchema>;export type ChatReply=z.infer<typeof ChatReplySchema>;
export type ChatBubble={id:string;role:'user'|'assistant';text:string;time:string;provider?:'data'|'openai';sources?:ChatReply['sources'];error?:boolean};
export const CHAT_HISTORY_KEY='tvu-data-conversation-v1';
export function restoreChatHistory(raw:string|null):ChatBubble[]{try{const values=JSON.parse(raw||'[]');if(!Array.isArray(values))return [];return values.filter((v:any)=>v&&typeof v.id==='string'&&v.id.length<100&&['user','assistant'].includes(v.role)&&typeof v.text==='string'&&v.text.length<=12000&&typeof v.time==='string'&&Number.isFinite(Date.parse(v.time))).map((v:any)=>({id:v.id,role:v.role,text:v.text,time:v.time,provider:v.provider==='openai'?'openai' as const:'data' as const,error:!!v.error,sources:Array.isArray(v.sources)?v.sources.map((s:unknown)=>ChatSourceSchema.safeParse(s)).filter((r:any)=>r.success).map((r:any)=>r.data).slice(0,5):[]}))}catch{return []}}
export function conversationRequest(messages:ChatBubble[]):ChatRequest{const eligible=messages.filter(m=>m.id!=='welcome'&&!m.error);const sources=[...eligible].reverse().find(m=>m.role==='assistant'&&m.sources?.length)?.sources||[];const recent=eligible.slice(-24).map(m=>({role:m.role,content:m.text.slice(0,4000)}));while(recent.length>1&&recent.reduce((n,m)=>n+m.content.length,0)>20000)recent.shift();return {messages:recent,context:{datasetIds:sources.map(s=>s.datasetId).slice(0,5)}}}
