import type {Config} from './model';
import {calculate,type Sheet} from './table-engine';
import {monthlyIdentity} from './monthly-identity';
import {orderedIds} from './home-layout';
export type DataMetadata={rawKey?:string;rawName?:string;recognition?:'pending'|'reviewed';enteredAt:string;summary:string;sourceId:string;connections:{search:boolean;watch:boolean;profile:boolean};mapping:{enabled:boolean;keyColumn:number;valueColumn:number;metric:number;year:number;status:'reference'|'verified'}};
export function dataMetadata(sheet:Sheet):DataMetadata{return sheet.metadata||{enteredAt:'',summary:'',sourceId:'',connections:{search:sheet.visible,watch:false,profile:false},mapping:{enabled:false,keyColumn:0,valueColumn:sheet.valueColumn,metric:0,year:2026,status:'reference'}}}
export function publicDataset(config:Config,id:string){return !!config.datasets.find(s=>s.id===id&&s.visible)||Object.values(config.home.blocks).some(b=>b.attachments.some(a=>a.datasetId===id))}
export function connectedRecords(config:Config){const generated:Config['records']=[];for(const sheet of config.datasets){const m=dataMetadata(sheet);if(!m.mapping.enabled||!publicDataset(config,sheet.id)||sheet.id.startsWith('demo-')||['recycling','realmeter-education'].includes(sheet.id))continue;const cells=calculate(sheet),found:Config['records']=[],seen=new Set<string>(),duplicates=new Set<string>();for(const row of cells){const key=String(row[m.mapping.keyColumn]?.value||'').trim(),value=row[m.mapping.valueColumn];if(!key||!value||value.error||typeof value.value!=='number')continue;const leader=monthlyIdentity(sheet.id,[key,sheet.id.startsWith('realmeter-')?String(row[1]?.value||''):''],config.leaders).leader;if(!leader?.regionId)continue;if(seen.has(leader.regionId)){duplicates.add(leader.regionId);continue}seen.add(leader.regionId);if((m.mapping.metric===4||m.mapping.metric===5)&&(!Number.isInteger(value.value)||value.value<1||value.value>5))continue;if([0,1,3].includes(m.mapping.metric)&&(value.value<0||value.value>100))continue;found.push({id:'dataset:'+sheet.id+':'+leader.regionId,regionId:leader.regionId,metric:m.mapping.metric,value:value.value,year:m.mapping.year,source:config.sources.find(s=>s.id===m.sourceId)?.url||'',status:m.mapping.status,note:sheet.title+(m.summary?' · '+m.summary:'')})}generated.push(...found.filter(r=>!duplicates.has(r.regionId)))}const counts=new Map<string,number>();for(const r of generated){const k=`${r.regionId}|${r.metric}|${r.year}`;counts.set(k,(counts.get(k)||0)+1)}const base=config.records.filter(r=>r.status!=='demo'||counts.get(`${r.regionId}|${r.metric}|${r.year}`)!==1),keys=new Set(base.map(r=>`${r.regionId}|${r.metric}|${r.year}`));for(const r of generated){const k=`${r.regionId}|${r.metric}|${r.year}`;if(!keys.has(k)&&counts.get(k)===1)base.push(r)}return base}
export function linkedProfileSheets(config:Config,leaderId:string){return config.datasets.filter(s=>publicDataset(config,s.id)&&dataMetadata(s).connections.profile&&s.rows.some(r=>monthlyIdentity(s.id,[r[dataMetadata(s).mapping.enabled?dataMetadata(s).mapping.keyColumn:0],s.id.startsWith('realmeter-')?r[1]:''],config.leaders).leader?.id===leaderId))}
export function attachDataset(config:Config,datasetId:string,target:string,newId:string):Config{const sheet=config.datasets.find(s=>s.id===datasetId);if(!sheet)throw new Error('데이터를 찾을 수 없습니다.');const id=target||newId,b=config.home.blocks[id]||{title:sheet.title,body:'',attachments:[]};if(b.attachments.length>=20)throw new Error('박스당 데이터는 최대 20개입니다.');if(b.attachments.some(a=>a.datasetId===datasetId))return config;return {...config,home:{...config.home,blocks:{...config.home.blocks,[id]:{...b,attachments:[...b.attachments,{datasetId,view:sheet.view,collapsed:true}]}},settings:{...config.home.settings,[id]:config.home.settings[id]||{collapsed:false,highlight:false}}}}}
export function addLayoutBlock(config:Config,after:string|null,id:string):Config{const main=['ask','monthly',...config.datasets.filter(s=>s.visible&&s.id!=='recycling'&&!s.id.startsWith('realmeter-')).map(s=>'dataset:'+s.id),'map',...(config.layout.showData?['watch']:[]),...(config.layout.showStories?['stories']:[]),...Object.keys(config.home.blocks).filter(k=>k.startsWith('custom:'))];const order=orderedIds(main,config.home.order);const at=after===null?0:order.indexOf(after)+1;order.splice(Math.max(0,at),0,id);return {...config,home:{...config.home,blocks:{...config.home.blocks,[id]:{title:'새 레이아웃',body:'',attachments:[]}},order:[...order,...config.home.order.filter(k=>!order.includes(k))],settings:{...config.home.settings,[id]:{collapsed:false,highlight:false}}}}}
export function connectRanking(config:Config,datasetId:string,scope:'basic'|'metro',direction:'high'|'low',weight:number,keyColumn:number,valueColumn:number):Config{const sheet=config.datasets.find(s=>s.id===datasetId);if(!sheet)throw new Error('연결할 데이터가 없습니다.');if(sheet.id.startsWith('demo-')||['recycling','realmeter-education'].includes(sheet.id))throw new Error('시연 자료·광역평균·교육감 자료는 단체장 종합순위에 연결할 수 없습니다.');if(!Number.isFinite(weight)||weight<=0||weight>100)throw new Error('가중치는 0 초과 100 이하로 입력하세요.');if(keyColumn>=sheet.columns.length||valueColumn>=sheet.columns.length)throw new Error('지역 열과 수치 열을 확인하세요.');const id='linked:'+datasetId+':'+scope,old=config.ranking.rules.find(r=>r.id===id);if(!old&&config.ranking.rules.length>=100)throw new Error('평가 지표는 최대 100개입니다.');const rule={id,title:sheet.title,enabled:true,kind:'dataset' as const,scope,datasetId,keyColumn,valueColumn,metric:0,year:2026,direction,weight};return {...config,ranking:{...config.ranking,rules:old?config.ranking.rules.map(r=>r.id===id?rule:r):[...config.ranking.rules,rule]}}}
export function searchDatasets(config:Config,query:string){const raw=query.trim().toLowerCase(),tokens=raw.replace(/비교해줘|보여줘|알려줘|비교|순위|상위\s*\d*\s*(명|곳|개)?|하위\s*\d*\s*(명|곳|개)?|전국|전체|데이터/g,' ').split(/[\s,]+/).map(x=>x.replace(/[과와의]$/,'')).filter(Boolean);const count=Math.max(1,Math.min(20,Number(raw.match(/(?:상위|하위)\s*(\d+)/)?.[1]||5)));return config.datasets.filter(s=>publicDataset(config,s.id)&&dataMetadata(s).connections.search).flatMap(s=>{const desc=[s.title,s.note,dataMetadata(s).summary].join(' ').toLowerCase(),rowMatches=s.rows.map((r,i)=>({r,i})).filter(({r})=>tokens.some(t=>[...r,monthlyIdentity(s.id,r,config.leaders).name].join(' ').toLowerCase().includes(t))),titleMatch=tokens.some(t=>desc.includes(t));if(tokens.length&&!titleMatch&&!rowMatches.length)return [];let indexes=(rowMatches.length?rowMatches:s.rows.map((r,i)=>({r,i}))).map(x=>x.i);const cells=calculate(s);if(/순위|상위|하위/.test(raw))indexes.sort((a,b)=>{const x=cells[a][s.valueColumn]?.value,y=cells[b][s.valueColumn]?.value;return (typeof x==='number'&&typeof y==='number'?y-x:0)*(raw.includes('하위')?-1:1)});return [{sheet:s,indexes:indexes.slice(0,count)}]})}
