import {digest,passwordHash,type AuthStore} from './sysop-auth';
const userKey=(username:string)=>digest(username).then(id=>'auth/members/'+id);
export const memberCookie=(token:string,maxAge=28800)=>`__Host-tvu_member=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('');
async function limited(req:Request,store:AuthStore,kind:string,max:number){const ip=req.headers.get('cf-connecting-ip')||req.headers.get('oai-authenticated-user-id')||'shared',key='auth/member-attempts/'+await digest(kind+ip),obj=await store.get(key),old=obj?await obj.json():null,now=Date.now(),rate=old&&old.until>now?old:{count:0,until:now+900000};if(rate.count>=max)return {allowed:false,key};const saved=await store.put(key,JSON.stringify({...rate,count:rate.count+1}),{onlyIf:obj?{etagMatches:obj.etag}:{etagDoesNotMatch:'*'}});return {allowed:!!saved,key}}
export async function registerMember(req:Request,store:AuthStore,input:{username:string;password:string;name:string;profile?:unknown}){const username=input.username.trim().toLowerCase(),name=input.name.trim();if(!/^[a-z0-9][a-z0-9_-]{3,39}$/.test(username)||username==='admin')return {status:400,error:'아이디는 admin을 제외한 영문·숫자·밑줄·하이픈 4~40자로 입력하세요.'};if(input.password.length<8||input.password.length>128||name.length<1||name.length>80)return {status:400,error:'이름과 8~128자 비밀번호를 입력하세요.'};if(!(await limited(req,store,'signup',10)).allowed)return {status:429,error:'가입 요청이 많습니다. 15분 후 다시 시도하세요.'};const salt=crypto.randomUUID(),key=await userKey(username),value={username,name,profile:cleanProfile(input.profile),plan:'free',status:'approved',until:'',salt,hash:await passwordHash(input.password,salt),version:crypto.randomUUID(),created:new Date().toISOString()};const saved=await store.put(key,JSON.stringify(value),{onlyIf:{etagDoesNotMatch:'*'}});return saved?{status:201}:{status:409,error:'이미 사용 중인 아이디입니다.'}}
export async function loginMember(req:Request,store:AuthStore,username:string,password:string){const rate=await limited(req,store,'login',10);if(!rate.allowed)return {status:429,error:'로그인 시도가 많습니다. 15분 후 다시 시도하세요.'};const key=await userKey(username.trim().toLowerCase()),obj=await store.get(key),a=obj?await obj.json():null;const check=await passwordHash(password,a?.salt||'tvu-unknown-account');if(!a||a.status==='withdrawn'||a.status==='pending'||a.hash!==check)return {status:401,error:'아이디 또는 비밀번호가 올바르지 않습니다.'};await store.delete(rate.key);const value=token();await store.put('auth/member-sessions/'+await digest(value),JSON.stringify({key,version:a.version,expires:Date.now()+28800000}));return {status:200,token:value,user:{username:a.username,name:a.name}}}
export async function memberSession(req:Request,store:AuthStore){const t=req.headers.get('cookie')?.match(/(?:^|;\s*)__Host-tvu_member=([a-f0-9]{64})(?:;|$)/)?.[1];if(!t)return null;const id=await digest(t),obj=await store.get('auth/member-sessions/'+id);if(!obj)return null;const s=await obj.json();if(s.expires<Date.now()||!/^auth\/members\/[a-f0-9]{64}$/.test(s.key))return null;const objA=await store.get(s.key),a=objA?await objA.json():null;if(!a||a.status==='withdrawn'||a.status==='pending'||a.version!==s.version)return null;return {id,user:{username:a.username,name:a.name,plan:effectivePlan(a)}}}

export function cleanProfile(input:unknown){const o=input&&typeof input==='object'?input as Record<string,unknown>:{};const value=(k:string,n:number)=>typeof o[k]==='string'?(o[k] as string).trim().slice(0,n):'';const birth=value('birth',6);if(birth&&!/^\d{6}$/.test(birth))throw Error('주민번호 앞 6자리만 입력하세요. 뒷자리는 저장하지 않습니다.');return {birth,phone:value('phone',30),address:value('address',300),organization:value('organization',150),gender:value('gender',30),email:value('email',200)}}
export function effectivePlan(a:any):'free'|'plus'|'pro'{return a.status!=='withdrawn'&&a.status!=='pending'&&['plus','pro'].includes(a.plan)&&Number.isFinite(Date.parse(a.until))&&Date.parse(a.until)>Date.now()?a.plan:'free'}
export async function listMembers(store:AuthStore,cursor?:string){if(!store.list)throw Error('회원 목록 저장소가 연결되지 않았습니다.');const page=await store.list({prefix:'auth/members/',limit:100,cursor});const members=await Promise.all(page.objects.map(async(o:any)=>{const obj=await store.get(o.key),a=obj?await obj.json():null;return a?{username:a.username,name:a.name,profile:cleanProfile(a.profile),plan:a.plan||'free',effectivePlan:effectivePlan(a),status:a.status||'approved',until:a.until||'',created:a.created,etag:obj.etag}:null}));return {members:members.filter(Boolean),cursor:page.truncated?page.cursor:null}}
export async function editMember(store:AuthStore,input:any){if(typeof input.username!=='string'||typeof input.etag!=='string')throw Error('회원과 버전 정보를 확인하세요.');const key=await userKey(input.username),obj=await store.get(key);if(!obj)return {status:404,error:'회원을 찾을 수 없습니다.'};const a=await obj.json();if(!['free','plus','pro'].includes(input.plan)||!['pending','approved','withdrawn'].includes(input.status))throw Error('등급과 승인 상태를 확인하세요.');if(input.until&&(!Number.isFinite(Date.parse(input.until))||input.until.length>50))throw Error('이용 종료일을 확인하세요.');const name=String(input.name||'').trim();if(!name||name.length>80)throw Error('이름을 입력하세요.');const next={...a,name,profile:cleanProfile(input.profile),plan:input.plan,status:input.status,until:input.until||'',version:input.status!==a.status?crypto.randomUUID():a.version};const saved=await store.put(key,JSON.stringify(next),{onlyIf:{etagMatches:input.etag}});return saved?{status:200}:{status:409,error:'회원 정보가 변경되었습니다. 새로 불러오세요.'}}
