import {subscriptionDefaults} from './subscription-defaults';
import { z } from 'zod';
import {defaultMapColors} from './map-style';
import collectedLeaders from './collected-leaders.json';
import tableDefaults from './table-defaults.json';
import {calculate} from './table-engine';
import railwayBaseline from './railway-baseline.json';
const text=(n=2000)=>z.string().max(n);
const safeURL=z.string().max(1000).refine(v=>!v||v.startsWith('/assets/')||/^\/api\/logo\?key=[a-f0-9-]+\.(png|jpg|webp)$/.test(v)||/^https:\/\//.test(v),'HTTPS 주소만 입력하세요');
export const metricNames=['재정자립도','재정자주도','통합재정수지','채무비율','종합청렴도','청렴체감도'];
export const ConfigSchema=z.object({
 subscription:z.object({title:text(150),description:text(500),note:text(500),plans:z.array(z.object({id:text(80),name:text(80),subtitle:text(300),monthly:z.number().int().min(0).max(100000000),annual:z.number().int().min(0).max(100000000),featured:z.boolean(),badge:text(80),features:z.array(text(300)).max(20),button:text(100)})).min(1).max(10)}).default(subscriptionDefaults),
 mapStyle:z.object({partyColors:z.record(z.string().regex(/^#[0-9a-fA-F]{6}$/)).default(defaultMapColors),partyFill:z.boolean().default(true),neighborBlur:z.number().min(0).max(3).default(.7)}).default({}),
 catalogVersion:z.number().int().min(0).max(100).default(0),
 ranking:z.object({baselineMonth:text(7).optional(),previousRanks:z.record(z.number().int().min(1).max(10000)).optional(),includeReference:z.boolean().default(true),rules:z.array(z.object({id:text(100),title:text(150),enabled:z.boolean(),kind:z.enum(['dataset','record']),scope:z.enum(['basic','metro']),datasetId:text(100),keyColumn:z.number().int().min(0).max(25),valueColumn:z.number().int().min(0).max(25),metric:z.number().int().min(0).max(5),year:z.number().int().min(1900).max(2200),direction:z.enum(['high','low']),weight:z.number().finite().min(0).max(100)})).max(100).default([{id:'rm-general',title:'단체장 직무평가',enabled:true,kind:'dataset',scope:'metro',datasetId:'realmeter-general',keyColumn:0,valueColumn:2,metric:0,year:2026,direction:'high',weight:1},{id:'rm-life',title:'주민생활 만족도',enabled:true,kind:'dataset',scope:'metro',datasetId:'realmeter-life',keyColumn:0,valueColumn:2,metric:0,year:2026,direction:'high',weight:1},{id:'rm-relative',title:'정당 대비 상대지수',enabled:true,kind:'dataset',scope:'metro',datasetId:'realmeter-relative',keyColumn:0,valueColumn:2,metric:0,year:2026,direction:'high',weight:1}])}).default({}),
 datasets:z.array(z.object({id:text(100),title:text(150),note:text(1500),visible:z.boolean(),metadata:z.object({enteredAt:text(50).refine(v=>!v||Number.isFinite(Date.parse(v)),'입력일시를 확인하세요').default(''),summary:text(1500).default(''),sourceId:text(80).default(''),connections:z.object({search:z.boolean().default(false),watch:z.boolean().default(false),profile:z.boolean().default(false)}).default({}),mapping:z.object({enabled:z.boolean().default(false),keyColumn:z.number().int().min(0).max(25).default(0),valueColumn:z.number().int().min(0).max(25).default(1),metric:z.number().int().min(0).max(5).default(0),year:z.number().int().min(1900).max(2200).default(2026),status:z.enum(['reference','verified']).default('reference')}).default({})}).optional(),view:z.enum(['table','striped','ranking','comparison','cards','bar','vertical','paired','line','mixed','pie','stacked','waterfall','histogram','bubble','scatter','population','radar3','radar4','radar5','radar6','radar7','radar8']),valueColumn:z.number().int().min(0).max(25),limit:z.number().int().min(0).max(500),columns:z.array(z.object({name:text(100),unit:text(30),formula:text(500)})).min(1).max(26),rows:z.array(z.array(text(500)).max(26)).max(500)})).max(50).default(tableDefaults as any),
 appearance:z.object({brandName:text(100).default('지방정부 tvU 데이터랩'),tagline:text(100).default('LOCAL GOVERNMENT DATA LAB'),logo:z.string().max(1000).refine(v=>!v||/^https:\/\//.test(v)||/^\/api\/logo\?key=[a-f0-9-]+\.(png|jpg|webp)$/.test(v),'로고는 HTTPS 또는 업로드 이미지를 사용하세요').default(''),logoText:text(8).default('L'),accent:z.string().regex(/^#[0-9a-fA-F]{6}$/).default('#9272c8'),background:z.string().regex(/^#[0-9a-fA-F]{6}$/).default('#faf9fd'),panel:z.string().regex(/^#[0-9a-fA-F]{6}$/).default('#ffffff'),text:z.string().regex(/^#[0-9a-fA-F]{6}$/).default('#352d43'),header:z.string().regex(/^#[0-9a-fA-F]{6}$/).default('#ffffff')}).default({}),
 home:z.object({blocks:z.record(z.object({title:text(150).default(''),body:text(2000).default(''),attachments:z.array(z.object({datasetId:text(100),collapsed:z.boolean().optional(),highlight:z.boolean().optional(),view:z.enum(['table','striped','ranking','comparison','cards','bar','vertical','paired','line','mixed','pie','stacked','waterfall','histogram','bubble','scatter','population','radar3','radar4','radar5','radar6','radar7','radar8'])})).max(20).default([])})).default({}),settings:z.record(z.object({collapsed:z.boolean(),highlight:z.boolean()})).default({}),order:z.array(text(120)).max(100).default([]),collapsed:z.boolean().default(true),animate:z.boolean().default(true)}).default({}),
 content:z.object({askTitle:text(100).default('데이터에 질문하기'),askAlign:z.enum(['left','center','right']).default('left'),title:text(100),subtitle:text(300),notice:text(500),rankingTitle:text(100),footer:text(300)}),
 layout:z.object({rankSide:z.enum(['right','left']),showRanking:z.boolean(),showStories:z.boolean(),showData:z.boolean(),compact:z.boolean(),accent:z.enum(['lavender','mint','blue','gold'])}),
 leaders:z.array(z.object({id:text(80),name:text(80),party:text(80).default('미확인'),role:text(100),regionId:text(80),photo:safeURL,career:text(1500),source:safeURL,level:z.enum(['basic','metro']).default('basic'),dataKey:text(100).default(''),asOf:text(30).default('2026-07'),historicalStatus:z.enum(['confirmed','pending']).default('pending'),policies:text(3000).default(''),pledges:text(3000).default(''),policySource:safeURL.default(''),pledgeSource:safeURL.default(''),photoSource:safeURL.default(''),collectedAt:text(30).default(''),score:z.number().min(0).max(100),change:z.number().min(-100).max(100)})).max(2000),
 records:z.array(z.object({id:text(100),regionId:text(80),metric:z.number().int().min(0).max(5),value:z.number().finite(),year:z.number().int().min(1900).max(2200),source:safeURL,status:z.enum(['demo','reference','verified']),note:text(500)})).max(10000),
 sources:z.array(z.object({id:text(80),name:text(100),url:safeURL,keyName:z.string().max(80).regex(/^$|^[A-Z][A-Z0-9_]*$/,"키 값 대신 KOSIS_API_KEY 같은 변수 이름만 입력하세요"),cycle:text(80),mapping:text(1500)})).max(200),
 stories:z.array(z.object({id:text(80),title:text(150),body:text(1500)})).max(50)
}).superRefine((c,ctx)=>{
 c.datasets.forEach((s,i)=>{
  if(s.metadata?.mapping.enabled&&(s.metadata.mapping.keyColumn>=s.columns.length||s.metadata.mapping.valueColumn>=s.columns.length))ctx.addIssue({code:'custom',path:['datasets',i],message:'지도에 연결할 지역·수치 열을 확인하세요'});
  if(s.valueColumn>=s.columns.length)ctx.addIssue({code:'custom',path:['datasets',i],message:'표의 수치 열을 선택하세요'});
  s.columns.forEach((col,j)=>{if(col.formula&&!col.formula.trim().startsWith('='))ctx.addIssue({code:'custom',path:['datasets',i,'columns',j],message:'열 수식은 =로 시작하세요'});});
  if(s.visible)calculate(s).forEach((row,r)=>row.forEach((cell,k)=>{if(cell.error)ctx.addIssue({code:'custom',path:['datasets',i,'rows',r,k],message:`${s.title} ${String.fromCharCode(65+k)}${r+1}: ${cell.error}`});}));
 });
for(const key of ['leaders','records','sources','stories','datasets'] as const){const ids=c[key].map(x=>x.id);if(new Set(ids).size!==ids.length)ctx.addIssue({code:'custom',message:key+' ID 중복'});}const tuples=c.records.map(r=>`${r.regionId}|${r.metric}|${r.year}`);if(new Set(tuples).size!==tuples.length)ctx.addIssue({code:'custom',message:'동일 지역·지표·연도 중복'});for(const r of c.records){if((r.metric===4||r.metric===5)&&(!Number.isInteger(r.value)||r.value<1||r.value>5))ctx.addIssue({code:'custom',message:'청렴도는 1~5 정수 등급'});if((r.metric===0||r.metric===1||r.metric===3)&&(r.value<0||r.value>100))ctx.addIssue({code:'custom',message:'비율은 0~100 범위'});}});
export type Config=z.infer<typeof ConfigSchema>;
export function normalizeConfig(input:unknown):Config{
 const config=ConfigSchema.parse(input);if(config.content.rankingTitle==='지자체장 종합순위')config.content.rankingTitle='월간 지자체 랭킹 TOP 10';if(config.home.blocks.ranking?.title==='지자체장 종합순위')config.home.blocks.ranking.title='월간 지자체 랭킹 TOP 10';if(config.catalogVersion>=1)return config;const leaders=[...config.leaders];
 for(const incoming of collectedLeaders){const at=leaders.findIndex(l=>incoming.regionId?l.regionId===incoming.regionId:l.name===incoming.name&&l.role===incoming.role);
  if(at<0){leaders.push(incoming as Config['leaders'][number]);continue}
  const old=leaders[at],legacy=old.source.includes('korean-eyes.com');leaders[at]={...old,level:incoming.level as 'basic'|'metro',dataKey:old.dataKey||incoming.dataKey,asOf:old.asOf||incoming.asOf,collectedAt:old.collectedAt||incoming.collectedAt,historicalStatus:incoming.historicalStatus==='confirmed'?'confirmed':old.historicalStatus,career:legacy?incoming.career||old.career:old.career||incoming.career,source:legacy?incoming.source:old.source||incoming.source,photo:old.photo||incoming.photo,photoSource:old.photoSource||incoming.photoSource,policies:old.policies||incoming.policies,pledges:old.pledges||incoming.pledges,policySource:old.policySource||incoming.policySource,pledgeSource:old.pledgeSource||incoming.pledgeSource};
 }
 return ConfigSchema.parse({...config,leaders,catalogVersion:1,content:{...config.content,notice:config.content.notice==='시연용 종합순위 · 점수는 임의로 구성했습니다. 실제 평가가 아닙니다.'?'종합순위는 등록한 지역 데이터의 상대 순위를 합산한 tvU 지수입니다.':config.content.notice}});
}
export const defaults:Config=normalizeConfig(railwayBaseline);
