import { z } from 'zod';
const text=(n=2000)=>z.string().max(n);
const safeURL=z.string().max(1000).refine(v=>!v||v.startsWith('/assets/')||/^https:\/\//.test(v),'HTTPS 주소만 입력하세요');
export const metricNames=['재정자립도','재정자주도','통합재정수지','채무비율','종합청렴도','청렴체감도'];
export const ConfigSchema=z.object({
 content:z.object({title:text(100),subtitle:text(300),notice:text(500),rankingTitle:text(100),footer:text(300)}),
 layout:z.object({rankSide:z.enum(['right','left']),showRanking:z.boolean(),showStories:z.boolean(),showData:z.boolean(),compact:z.boolean(),accent:z.enum(['lavender','mint','blue','gold'])}),
 leaders:z.array(z.object({id:text(80),name:text(80),role:text(100),regionId:text(80),photo:safeURL,career:text(1500),source:safeURL,score:z.number().min(0).max(100),change:z.number().min(-100).max(100)})).max(2000),
 records:z.array(z.object({id:text(100),regionId:text(80),metric:z.number().int().min(0).max(5),value:z.number().finite(),year:z.number().int().min(1900).max(2200),source:safeURL,status:z.enum(['demo','reference','verified']),note:text(500)})).max(10000),
 sources:z.array(z.object({id:text(80),name:text(100),url:safeURL,keyName:z.string().max(80).regex(/^$|^[A-Z][A-Z0-9_]*$/,"키 값 대신 KOSIS_API_KEY 같은 변수 이름만 입력하세요"),cycle:text(80),mapping:text(1500)})).max(200),
 stories:z.array(z.object({id:text(80),title:text(150),body:text(1500)})).max(50)
}).superRefine((c,ctx)=>{for(const key of ['leaders','records','sources','stories'] as const){const ids=c[key].map(x=>x.id);if(new Set(ids).size!==ids.length)ctx.addIssue({code:'custom',message:key+' ID 중복'});}const tuples=c.records.map(r=>`${r.regionId}|${r.metric}|${r.year}`);if(new Set(tuples).size!==tuples.length)ctx.addIssue({code:'custom',message:'동일 지역·지표·연도 중복'});for(const r of c.records){if((r.metric===4||r.metric===5)&&(!Number.isInteger(r.value)||r.value<1||r.value>5))ctx.addIssue({code:'custom',message:'청렴도는 1~5 정수 등급'});if((r.metric===0||r.metric===1||r.metric===3)&&(r.value<0||r.value>100))ctx.addIssue({code:'custom',message:'비율은 0~100 범위'});}});
export type Config=z.infer<typeof ConfigSchema>;
export const defaults:Config={content:{title:'대한민국, 데이터로 읽다',subtitle:'지도를 누르면 지역이 보이고, 지역을 누르면 정책과 사람이 보입니다.',notice:'시연용 종합순위 · 점수는 임의로 구성했습니다. 실제 평가가 아닙니다.',rankingTitle:'지자체장 종합순위',footer:'지방자치연구소(주) · 월간 지방정부 · tvU'},layout:{rankSide:'right',showRanking:true,showStories:true,showData:true,compact:false,accent:'lavender'},leaders:[
{id:'choi',name:'최상기',role:'인제군수',regionId:'51810',photo:'/assets/choi-sang-ki.jpg',career:'인제군 부군수\n후보 등록 당시 인제군수',source:'https://korean-eyes.com/local/100163065',score:92.4,change:2},
{id:'oh',name:'오세훈',role:'서울특별시장',regionId:'11',photo:'/assets/oh.jpg',career:'경력 원자료 입력 대기',source:'https://korean-eyes.com/local/100162984',score:89.8,change:1},
{id:'chumi',name:'추미애',role:'경기도지사',regionId:'41',photo:'/assets/chumi.jpg',career:'경력 원자료 입력 대기',source:'https://korean-eyes.com/local/100163148',score:87.6,change:-1},
{id:'jeon',name:'전재수',role:'부산광역시장',regionId:'26',photo:'/assets/jeon.jpg',career:'경력 원자료 입력 대기',source:'https://korean-eyes.com/local/100163192',score:85.2,change:3},
{id:'park',name:'박찬대',role:'인천광역시장',regionId:'28',photo:'/assets/park.jpg',career:'경력 원자료 입력 대기',source:'https://korean-eyes.com/local/100163128',score:83.7,change:-2},
{id:'choo',name:'추경호',role:'대구광역시장',regionId:'27',photo:'/assets/choo.jpg',career:'경력 원자료 입력 대기',source:'https://korean-eyes.com/local/100163199',score:81.9,change:0}],records:[8.62,66.75,-4.71,0,3,2].map((value,i)=>({id:'inje-'+i,regionId:'51810',metric:i,value,year:i===3?2024:i>=4?2025:2026,source:'https://korean-eyes.com/local/100163065',status:'reference',note:'참고 페이지 표시값 · 원기관 대조 전'})),sources:[{id:'kosis',name:'KOSIS 공유서비스',url:'https://kosis.kr/openapi/',keyName:'KOSIS_API_KEY',cycle:'원자료 공표 주기',mapping:'연동 설계 대기: 지역코드, 지표, 기간, 수치 필드를 매핑합니다.'},{id:'lofin',name:'지방재정365',url:'https://www.lofin365.go.kr/',keyName:'LOFIN_API_KEY',cycle:'연간',mapping:'데이터셋별 API 주소·회계 기준·호출 한도 확인 필요'}],stories:[{id:'tour',title:'관광시설, 투자 이후를 묻다',body:'조성비·운영비·방문객과 지역 소비를 함께 보는 취재 기획입니다.'},{id:'budget',title:'못 쓴 예산의 이유는 무엇인가',body:'불용과 이월을 구분하고 주요 사업 지연 원인을 취재합니다.'},{id:'youth',title:'청년이 떠나는 곳, 머무는 곳',body:'순이동의 변화와 주거·일자리 정책을 대조합니다.'}]};
