export type AuthStore={list?:(options:any)=>Promise<any>;get:(key:string)=>Promise<any>;put:(key:string,value:string,options?:any)=>Promise<any>;delete:(key:string)=>Promise<any>};
const key='auth/sysop.json',encoder=new TextEncoder();
export async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function passwordHash(password:string,salt:string){const material=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);return Array.from(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:encoder.encode(salt),iterations:100000},material,256))).map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function account(store:AuthStore){let obj=await store.get(key);if(!obj){const salt=crypto.randomUUID(),value={username:'admin',salt,hash:await passwordHash('1111',salt),version:crypto.randomUUID(),initial:true};await store.put(key,JSON.stringify(value),{onlyIf:{etagDoesNotMatch:'*'}});obj=await store.get(key)}if(!obj)throw Error('계정을 초기화하지 못했습니다.');return {value:await obj.json(),etag:obj.etag}}
export const cookie=(token:string,maxAge=28800)=>`__Host-tvu_sysop=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;
export async function session(req:Request,store:AuthStore){const token=req.headers.get('cookie')?.match(/(?:^|;\s*)__Host-tvu_sysop=([a-f0-9]{64})(?:;|$)/)?.[1];if(!token)return null;const id=await digest(token),obj=await store.get('auth/sessions/'+id);if(!obj)return null;const value=await obj.json();if(value.expires<Date.now())return null;const a=await store.get(key);if(!a||value.version!==(await a.json()).version)return null;return {id,...value}}
export async function login(req:Request,store:AuthStore,username:string,password:string){const ip=req.headers.get('cf-connecting-ip')||req.headers.get('oai-authenticated-user-id')||'shared';const rateKey='auth/attempts/'+await digest(ip),attempt=await store.get(rateKey),old=attempt?await attempt.json():null;const now=Date.now(),rate=old&&old.until>now?old:{count:0,until:now+900000};if(rate.count>=5)return {status:429,error:'로그인 시도가 많습니다. 15분 후 다시 시도해 주세요.'};const a=(await account(store)).value;if(username!==a.username||await passwordHash(password,a.salt)!==a.hash){const saved=await store.put(rateKey,JSON.stringify({...rate,count:rate.count+1}),{onlyIf:attempt?{etagMatches:attempt.etag}:{etagDoesNotMatch:'*'}});return {status:saved?401:429,error:'아이디 또는 비밀번호가 올바르지 않습니다.'}}await store.delete(rateKey);const token=Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('');await store.put('auth/sessions/'+await digest(token),JSON.stringify({version:a.version,expires:now+28800000}));return {status:200,token,initial:a.initial}}
export async function changePassword(store:AuthStore,current:string,next:string){const a=await account(store);if(await passwordHash(current,a.value.salt)!==a.value.hash)return {status:400,error:'현재 비밀번호가 올바르지 않습니다.'};if(next.length<4||next.length>128||next===current)return {status:400,error:'새 비밀번호는 현재와 다른 4~128자로 입력하세요.'};const salt=crypto.randomUUID();const saved=await store.put(key,JSON.stringify({...a.value,salt,hash:await passwordHash(next,salt),version:crypto.randomUUID(),initial:false}),{onlyIf:{etagMatches:a.etag}});return saved?{status:200}:{status:409,error:'계정 정보가 변경되었습니다. 다시 로그인해 주세요.'}}
