"use client";
import {useState} from 'react';
import type {Config} from '../lib/model';
import {searchDatasets} from '../lib/data-connections';
import {calculate} from '../lib/table-engine';
import MonthlySheet from './monthly-sheet';
import data from '../lib/productivity-data.json';
export function DataEntry({title='데이터에 질문하기',align='left',config}:{title?:string;align?:'left'|'center'|'right';config?:Config}={}){const [q,setQ]=useState(''),[submitted,setSubmitted]=useState('');const results=config&&submitted?searchDatasets(config,submitted):[];return <section className="panel data-entry"><span className="section-label">ASK tvU · DATA EXPLORER</span><h2 style={{textAlign:align}}>{title}</h2><p>지역을 비교하고, 저장된 수치와 그래프를 확인하세요.</p><form action={config?undefined:'/ask.html'} onSubmit={config?e=>{e.preventDefault();setSubmitted(q.trim())}:undefined}><input name="q" aria-label="데이터 질문" value={q} onChange={e=>setQ(e.target.value)} placeholder="예: 서울과 부산 직무평가 비교" maxLength={500}/><button>검색하기 →</button></form><div className="data-chips">{['단체장 직무평가 상위 5명','서울과 부산 비교해줘','주민생활 만족도 하위 3곳'].map(t=>config?<button key={t} onClick={()=>{setQ(t);setSubmitted(t)}}>{t} ↗</button>:<a key={t} href={'/ask.html?q='+encodeURIComponent(t)}>{t} ↗</a>)}</div><small>관리자가 검색에 연결한 공개 자료 기반 · 원수치 검색·비교 · 생성형 AI 미연결</small>{submitted&&config&&<div className="dataset-search-results" aria-live="polite"><h3>‘{submitted}’ 검색 결과</h3>{!results.length?<p>연결된 공개 자료에서 일치하는 데이터를 찾지 못했습니다. 제목 또는 지역명으로 검색하세요.</p>:results.map(({sheet,indexes})=>{const cells=calculate(sheet),preview={...sheet,view:'table' as const,columns:sheet.columns.map(c=>({...c,formula:''})),rows:indexes.map(i=>cells[i].map(c=>c.error?'확인 필요':String(c.value))),limit:0};return <details key={sheet.id} open><summary>{sheet.title} · {indexes.length}행</summary><MonthlySheet sheet={preview} leaders={config.leaders} animated={false}/></details>})}</div>}</section>}
export function ProductivityGraph(){return <section className="panel productivity-panel"><span className="section-label">2025 생산성 평가 · 환경 세부지표</span><div className="row-title"><h2>생활계폐기물 재활용률 상위 5개 지역</h2><a href="/productivity-2025.html">자료 전체 보기 ↗</a></div><p>관할 기초지자체의 재활용률을 광역별로 평균한 수치입니다.</p><div className="bar-axis"><span>0%</span><span>50%</span><span>100%</span></div>{data.recycling_chart.top5.map((r,i)=><div className="productivity-bar" key={r.region}><b>{i+1} {r.region}</b><div className="productivity-track"><div style={{width:r.value+'%',background:i===0?'#7950a7':'#b59ace'}}/></div><strong>{r.value.toFixed(2)}<small>%</small></strong></div>)}<p className="muted tiny">생산성 종합점수 순위가 아닙니다. 보고서 전국 평균: 53.49%.<br/>출처: 한국생산성본부, 2025년 생산성지수 측정 최종보고서 75쪽, 그림 Ⅱ-46.</p></section>}
export function RealmeterPanel(){return <section className="panel realmeter-panel"><div className="row-title"><h2>리얼미터 광역단체 평가</h2><a href="/realmeter-2026-07.html">전체 화면 ↗</a></div><iframe title="리얼미터 2026년 7월 광역단체 평가 4개 지표" src="/realmeter-2026-07.html?embed=1" style={{border:0,width:'100%',height:1050,borderRadius:16}}/></section>}
