'use client';
import {useState,type ReactNode} from 'react';
import {blockSetting,type BlockSetting} from '../lib/home-settings';
import {orderedIds,moveBlock} from '../lib/home-layout';
export type HomeBlock={id:string;title:string;titleAlign?:'left'|'center'|'right';content:ReactNode};
export function HomeBlocks({blocks,order,editing=false,collapsed=true,settings,animated=true,onOrder,onSelect}:{blocks:HomeBlock[];order:string[];editing?:boolean;collapsed?:boolean;settings?:Record<string,BlockSetting>;animated?:boolean;onOrder?:(ids:string[])=>void;onSelect?:(id:string)=>void}){
 const [drag,setDrag]=useState(''),[target,setTarget]=useState('');const ids=orderedIds(blocks.map(b=>b.id),order);
 function move(from:string,to:string){onOrder?.(moveBlock(ids,from,to));setDrag('');setTarget('')}
 return <div className={'home-blocks '+(editing?'is-editing ':'')+(animated?'has-animation':'')}>
 {ids.map((id,i)=>{const b=blocks.find(x=>x.id===id)!;const setting=settings?blockSetting(id,settings):{collapsed,highlight:false};return <div key={id+':'+setting.collapsed} data-block-id={id} className={'home-block '+(target===id?'drop-target':'')} onDragOver={editing?e=>{if(drag){e.preventDefault();e.dataTransfer.dropEffect='move';setTarget(id)}}:undefined} onDrop={editing?e=>{e.preventDefault();move(drag,id)}:undefined}>
 {editing&&<div className="block-edit-tools">{onOrder&&<><button draggable onDragStart={e=>{setDrag(id);e.dataTransfer.setData('text/plain',id);e.dataTransfer.effectAllowed='move'}} onDragEnd={()=>{setDrag('');setTarget('')}} className="drag-handle" aria-label={b.title+' 박스 이동'}>⠿ 마우스로 잡아 이동</button><button disabled={i===0} onClick={()=>move(id,ids[i-1])} aria-label={b.title+' 위로 이동'}>↑</button><button disabled={i===ids.length-1} onClick={()=>move(id,ids[i+1])} aria-label={b.title+' 아래로 이동'}>↓</button></>}<button className="primary" onClick={()=>onSelect?.(id)}>이 박스 편집</button></div>}
 <details className="home-disclosure" open={!setting.collapsed?true:undefined}><summary><div className="disclosure-title" style={{flex:1,textAlign:b.titleAlign||'left',alignItems:b.titleAlign==='center'?'center':b.titleAlign==='right'?'flex-end':'flex-start'}}>{setting.highlight&&<span className="title-crown" role="img" aria-label="강조"><svg width="17" height="16" viewBox="0 0 24 20" aria-hidden="true"><path d="M2 5 7 9 12 2 17 9 22 5 20 16H4Z M4 19H20" fill="currentColor" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></svg></span>}<h2>{b.title}</h2></div><span className="disclosure-arrow" aria-hidden="true">⌄</span><span className="sr-only">펼치기 또는 접기</span></summary><div className="disclosure-content">{b.content}</div></details></div>})}</div>
}
