'use client';
import {calculate} from '../lib/table-engine';
import {useState} from 'react';
import {dataMetadata,publicDataset} from '../lib/data-connections';
import MonthlySheet from './monthly-sheet';
import type {Config} from '../lib/model';
export function WatchData({config}:{config?:Config}={}){const linked=config?.datasets.filter(s=>publicDataset(config,s.id)&&dataMetadata(s).connections.watch)||[];if(config&&linked.length)return <section className="panel watch-panel connected-watch"><div className="row-title"><h2>눈여겨볼 데이터</h2><span className="chip">연결된 공개 자료</span></div>{linked.map(s=><details key={s.id} open><summary>{s.title}</summary><MonthlySheet sheet={s} leaders={config.leaders} animated={config.home.animate}/></details>)}</section>;return <section className="panel watch-panel"><div className="row-title"><div><span className="section-label">2026 DATA WATCH</span><h2>2026 눈여겨볼 데이터</h2></div><span className="chip">기획 · 시연</span></div><p className="muted">숫자의 변화에서 지방정부의 다음 과제를 발견합니다.</p><div className="watch-grid"><a href="#insight/population" className="watch-card"><span>01 / POPULATION</span><h3>2026 인구증가 지자체</h3><div className="mini-bars"><i/><i/><i/><i/></div><p>인구가 늘어나는 지역, 무엇이 다른가</p><b>지역별 그래프 보기 →</b></a><a href="#insight/integrity" className="watch-card integrity"><span>02 / INTEGRITY</span><h3>2026 청렴도 1위 지자체</h3><div className="watch-medal">1<span>등급</span></div><p>신뢰받는 행정의 조건을 살펴보다</p><b>지역별 그래프 보기 →</b></a></div><div className="analysis-preview"><div><span className="section-label">DATA ANALYSIS</span><h3>데이터 분석</h3><p>인구 증가는 전입의 결과일까, 출생의 변화일까?<br/>청렴도 등급 뒤에 있는 행정의 차이를 읽습니다.</p><small>분석 방향 미리보기 · 실제 원자료 검수 후 발행</small></div></div><div className="watch-premium-fade" aria-hidden="true"/><div className="watch-premium-center"><a className="premium-button" href="#subscribe">✦ 프리미엄 구독 <span>→</span></a></div></section>}
export function InsightPage({kind,leaders,datasets}:{kind:string;leaders:Config['leaders'];datasets:Config['datasets']}){const [replay,setReplay]=useState(0);const population=kind==='population';const sheet=datasets.find(s=>s.id===(population?'demo-population':'demo-integrity'));const cells=sheet?calculate(sheet):[];const list=leaders.filter(l=>cells.some(r=>r[0]?.value===l.id));const values=list.map(l=>{const r=cells.find(r=>r[0]?.value===l.id);return typeof r?.[1]?.value==='number'?r[1].value:0});return <section className="panel insight-page"><div className="breadcrumb"><a href="#map/KR">대한민국</a> / <a href="#watch">2026 눈여겨볼 데이터</a> / {population?'인구증가':'청렴도'}</div><span className="section-label">2026 / {population?'POPULATION CHANGE':'PUBLIC INTEGRITY'}</span><h2>{population?'2026 인구증가 지자체':'2026 청렴도 1위 지자체'}</h2><p className="muted">{population?'지역의 변화를 한눈에 읽는 인구증가율 비교':'최상위 청렴등급을 함께 살펴보는 지역 비교'}</p><div className="chart-disclaimer"><b>디자인 시연용 · 실제 2026 순위 아님</b><p>사진은 기존 참고 프로필이며 아래 수치와 등급은 화면 구현을 위한 가상값입니다. 실제 인구증가·청렴도 성과를 의미하지 않습니다.</p></div><div className="row-title"><span className="chip">{population?'전년 대비 증가율 · 가상값':'1위 테마 / 동일 1등급 예시'}</span><button className="button subtle" onClick={()=>setReplay(v=>v+1)}>↻ 다시 재생</button></div><div className="horizontal-chart" key={kind+replay}>{list.map((l,i)=><a href={'#leader/'+l.id} className="horizontal-row" key={l.id} style={{animationDelay:i*100+'ms'}}><span className="chart-rank">{population?i+1:'공동'}</span><img src={l.photo} alt={l.name} onError={e=>{e.currentTarget.style.visibility='hidden'}}/><div className="chart-person"><strong>{l.role}</strong><small>{l.name} · 참고 인물</small></div><div className="horizontal-track"><div className={'horizontal-fill '+(!population?'integrity-fill':'')} style={{width:population?(Math.abs(values[i])/Math.max(1,...values.map(Math.abs))*100)+'%':'100%',animationDelay:i*110+'ms'}}/></div><b>{population?'+'+values[i].toFixed(1)+'%':values[i]+'등급'}</b></a>)}</div><div className="chart-notes"><h3>그래프 읽는 법</h3><p>{population?'증가율 = (비교 시점 인구 − 기준 시점 인구) ÷ 기준 시점 인구 × 100. 실데이터 발행 시 기준 월, 주민등록인구 범위, 행정구역 변경 여부를 함께 표시합니다.':'청렴도 1등급은 단독 1위와 다릅니다. 같은 등급은 같은 길이의 막대로 표시하고 등급 안에서 임의의 우열을 매기지 않습니다.'}</p><p>자료 상태: 원자료 미연결 · 기준기간 미확정 · 가상 예시. 광역·기초 혼합은 디자인 확인용입니다.</p></div><div className="analysis-preview"><div><h3>{population?'사람이 모이는 지역의 공통점은?':'청렴한 조직은 어떻게 만들어지는가?'}</h3><p>비교 기준과 정책 맥락까지 읽는 데이터 분석을 준비합니다.</p></div><a className="premium-button" href="#subscribe">✦ 프리미엄 구독 →</a></div></section>}
export {SubscriptionPage} from './subscription-page';
