'use client';
import {useState} from 'react';
import type {Config} from '../lib/model';
import {compositeRanking} from '../lib/ranking';
import {Avatar} from './dashboard';
export function RankCrown({rank}:{rank:number}){return rank<=3?<span className={'rank-crown crown-'+rank} role="img" aria-label={rank+'위 '+(['','금','은','동'][rank])+'색 왕관'}><svg width="23" height="22" viewBox="0 0 24 20" aria-hidden="true"><path d="M2 5 7 9 12 2 17 9 22 5 20 16H4Z M4 19H20" fill="currentColor" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></svg></span>:null}
export function RankingBoard({config}:{config:Config}){const [scope,setScope]=useState<'basic'|'metro'>('metro'),[limit,setLimit]=useState(10);const result=compositeRanking(config,scope);
 return <aside className="ranking panel"><span className="section-label">LIVE DATA RANKING</span><h2>{config.content.rankingTitle}</h2><div className="ranking-scope"><button aria-pressed={scope==='basic'} onClick={()=>{setScope('basic');setLimit(10)}}>기초단체장</button><button aria-pressed={scope==='metro'} onClick={()=>{setScope('metro');setLimit(10)}}>광역단체장</button></div><p className="tiny muted">등록 데이터 순위를 종합한 tvU 계산값 · 개인의 전체 성과를 평가한 공식 순위가 아닙니다. 발행 변경을 15초 간격으로 확인합니다.</p>{result.reason?<p className="callout">{result.reason}</p>:<><span className="chip">{result.rules.length}개 지표 · {result.rows.length}곳 비교</span>{result.rows.slice(0,limit).map(row=><a className="rank-row" href={'#leader/'+row.leader.id} key={row.leader.id}><div className="rank-place"><RankCrown rank={row.rank}/><span className="rank-num">{row.rank}</span></div><Avatar src={row.leader.photo} name={row.leader.name} party={row.leader.party}/><div className="rank-info"><strong>{row.leader.name}</strong><small>{row.leader.role} · {row.leader.party}</small><div className="rank-track"><i style={{width:row.score+'%'}}/></div></div><div className="rank-score"><b>{row.score.toFixed(1)}</b><small>종합지수</small></div></a>)}{limit<result.rows.length&&<button onClick={()=>setLimit(n=>n+10)}>더 보기</button>}</>}<details className="ranking-method"><summary>계산 기준·제외 지역</summary><p>각 지표의 순위를 0~100 상대지수로 환산한 뒤 가중평균합니다. 동률은 동일 순위와 동일 점수입니다. 모든 선택 지표가 있는 지역만 비교하며 미입력을 0점으로 채우지 않습니다.</p>{result.rules.map(r=><p key={r.id} className="tiny">{r.title} · 가중치 {r.weight} · {r.direction==='high'?'높을수록 우수':'낮을수록 우수'}{r.kind==='record'?' · '+r.year+'년':''}</p>)}<p>자료 부족으로 제외: {result.excluded.length}곳</p><p className="tiny">광역의 리얼미터 자료와 기초지자체·교육감 자료를 임의로 합산하지 않습니다. 재활용률의 광역별 기초지자체 평균은 직접적인 광역정부 성과값으로 사용하지 않습니다.</p></details></aside>
}
