'use client';
import {useEffect,useState,type ReactNode,type CSSProperties} from 'react';
import type {Config} from '../lib/model';
import {rankingThemes,rankComparisonKey} from '../lib/ranking-themes';
import {Avatar} from './dashboard';
export function RankCrown({rank}:{rank:number}){return rank<=3?<span className={'rank-crown crown-'+rank} role="img" aria-label={rank+'위 '+(['','금','은','동'][rank])+'색 왕관'}><svg width="23" height="22" viewBox="0 0 24 20" aria-hidden="true"><path d="M2 5 7 9 12 2 17 9 22 5 20 16H4Z M4 19H20" fill="currentColor" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></svg></span>:null}
export function RankFlapCard({content,signature,delay,href,label}:{content:ReactNode;signature:string;delay:number;href:string;label:string}){const [frame,setFrame]=useState({signature,content,previous:content,turn:1});useEffect(()=>{setFrame(old=>old.signature===signature?old:{signature,content,previous:old.content,turn:old.turn+1})},[signature,content]);return <a href={href} className="rank-flap-slot" aria-label={label} style={{'--rank-delay':delay+'ms'} as CSSProperties}><div className="rank-flap-base">{frame.content}</div><div key={frame.turn} className="rank-flap-stage" aria-hidden="true"><div className="rank-flap-half rank-flap-old-bottom">{frame.previous}</div><div className="rank-flap-half rank-flap-top">{frame.previous}</div><div className="rank-flap-half rank-flap-bottom">{frame.content}</div></div></a>}
export function RankingBoard({config}:{config:Config}){const [scope,setScope]=useState<'basic'|'metro'>('metro'),[index,setIndex]=useState(0),[paused,setPaused]=useState(false),[hover,setHover]=useState(false);const themes=rankingThemes(config,scope),theme=themes[index%themes.length],result=theme.result;
 useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)setPaused(true)},[]);
 useEffect(()=>{if(paused||hover||themes.length<2)return;const timer=setInterval(()=>setIndex(n=>(n+1)%themes.length),10000);return()=>clearInterval(timer)},[paused,hover,themes.length]);
 return <aside className="ranking panel monthly-ranking" onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)} onFocusCapture={()=>setHover(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setHover(false)}}><span className="section-label">MONTHLY · TOP 10</span><h2>월간 지자체 랭킹 TOP 10</h2><div className="ranking-scope"><button aria-pressed={scope==='basic'} onClick={()=>{setScope('basic');setIndex(0)}}>기초단체장</button><button aria-pressed={scope==='metro'} onClick={()=>{setScope('metro');setIndex(0)}}>광역단체장</button></div><div className="ranking-departure"><strong className="ranking-theme-title">{theme.id==='composite'?<><RankCrown rank={1}/>종합랭킹 TOP 10</>:theme.title}</strong></div><p className="tiny muted">활성화한 평가 테마와 종합랭킹을 10초마다 순환합니다. 마우스를 올리면 멈춥니다.</p>{result.reason?<p className="callout">{result.reason}</p>:<><span className="chip">{result.rules.length}개 지표 · {result.rows.length}곳 비교</span>{result.rows.slice(0,10).map((row,i)=>{const previous=config.ranking.previousRanks?.[rankComparisonKey(config,scope,theme,row.leader.id)],delta=previous===undefined?null:previous-row.rank;const content=<div className="rank-row"><div className="rank-place"><RankCrown rank={row.rank}/><span className="rank-num">{row.rank}</span></div><Avatar src={row.leader.photo} name={row.leader.name} party={row.leader.party}/><div className="rank-info"><strong>{row.leader.name}</strong><small>{row.leader.role} · {row.leader.party}</small><div className="rank-track"><i style={{width:row.score+'%'}}/></div></div><div className="rank-score"><b>{(theme.id==='composite'?row.score:row.contributions[0].value).toFixed(1)}</b><small>{theme.id==='composite'?'종합지수':'원수치'}</small><span className={'rank-change '+(delta===null?'unknown':delta>0?'up':delta<0?'down':'same')} title={delta===null?'비교 기준 자료가 없습니다.':'비교 기준 '+config.ranking.baselineMonth}>{delta===null?'—':delta>0?'▲ +'+delta:delta<0?'▼ '+delta:'— 0'}</span></div></div>;return <RankFlapCard key={i} signature={JSON.stringify([scope,theme.id,row.leader.id,row.rank,row.score,row.contributions,delta,row.leader.photo,row.leader.name,row.leader.party])} content={content} delay={i*140} href={'#leader/'+row.leader.id} label={row.rank+'위 '+row.leader.name+' · '+theme.title}/>})}</>}<p className="tiny muted">순위 변동 기준: {config.ranking.baselineMonth||'비교자료 없음'} · 동일 평가 기준·비교 지역이 일치할 때만 계산합니다.</p><details className="ranking-method"><summary>계산 기준·제외 지역</summary><p>종합지수는 지표별 상대순위의 가중평균입니다. 테마별 원수치 순위와 개인의 전체 성과를 평가한 공식 순위를 구분하세요. 동률은 동일 순위입니다. 등록 자료의 기준월은 각 자료 출처를 확인하세요.</p>{result.rules.map(r=><p key={r.id} className="tiny">{r.title} · 가중치 {r.weight} · {r.direction==='high'?'높을수록 우수':'낮을수록 우수'}</p>)}<p>자료 부족으로 제외: {result.excluded.length}곳</p><p className="tiny">광역의 리얼미터 자료와 기초지자체·교육감 자료를 임의로 합산하지 않습니다. 재활용률의 광역별 기초지자체 평균은 직접적인 광역정부 성과값으로 사용하지 않습니다.</p></details></aside>
}
