import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {ConfigSchema,defaults,normalizeConfig} from './model.bundle.mjs';
import {login,session,changePassword,cookie} from './auth.bundle.mjs';
import {calculate} from './table.bundle.mjs';
const root=path.dirname(fileURLToPath(import.meta.url)),data=path.resolve(process.env.DATA_DIR||path.join(root,'data')),port=Number(process.env.PORT||3000),origin=process.env.PUBLIC_ORIGIN||(process.env.RAILWAY_PUBLIC_DOMAIN?'https://'+process.env.RAILWAY_PUBLIC_DOMAIN:undefined),previewPassword=process.env.PREVIEW_PASSWORD;
if(!origin||(!origin.startsWith('https://')&&!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin)))throw Error('PUBLIC_ORIGIN 또는 Railway 도메인 설정이 필요합니다.');
for(const folder of ['raw','history','auth','logos'])await fs.mkdir(path.join(data,folder),{recursive:true});
const hash=v=>crypto.createHash('sha256').update(v).digest('hex'),digest=v=>crypto.createHash('sha256').update(v).digest();
const previewAuth=req=>{if(!previewPassword)return true;const h=req.headers.authorization||'';return h.startsWith('Basic ')&&crypto.timingSafeEqual(digest(Buffer.from(h.slice(6),'base64').toString()),digest((process.env.ADMIN_USER||'admin')+':'+previewPassword))};
let queue=Promise.resolve();function serial(fn){const job=queue.then(fn);queue=job.catch(()=>{});return job}
async function atomic(file,text){await fs.mkdir(path.dirname(file),{recursive:true});const temp=file+'.'+crypto.randomUUID()+'.tmp';await fs.writeFile(temp,text,{mode:0o600});await fs.rename(temp,file)}
const authStore={async get(key){try{const text=await fs.readFile(path.join(data,key),'utf8');return {etag:hash(text),json:async()=>JSON.parse(text)}}catch(e){if(e.code==='ENOENT')return null;throw e}},async put(key,text,options){return serial(async()=>{const old=await this.get(key),check=options?.onlyIf;if(check?.etagDoesNotMatch==='*'&&old||check?.etagMatches&&old?.etag!==check.etagMatches)return null;await atomic(path.join(data,key),text);return {etag:hash(text)}})},async delete(key){await fs.rm(path.join(data,key),{force:true})}};
async function read(name){try{const text=await fs.readFile(path.join(data,name),'utf8');return {config:normalizeConfig(JSON.parse(text)),etag:hash(text),updated:(await fs.stat(path.join(data,name))).mtime.toISOString()}}catch(e){if(e.code==='ENOENT')return {config:defaults,etag:null,updated:null};throw e}}
async function write(name,config,etag){const old=await read(name);if(old.etag!==etag)throw Object.assign(Error('다른 편집이 먼저 저장되었습니다. 다시 불러오세요.'),{status:409});await atomic(path.join(data,name),JSON.stringify(ConfigSchema.parse(config)));return read(name)}
const json=(res,value,status=200,headers={})=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(value))};
async function body(req,max=6000000){let size=0,chunks=[];for await(const c of req){size+=c.length;if(size>max)throw Object.assign(Error('입력 크기 제한을 초과했습니다.'),{status:413});chunks.push(c)}return Buffer.concat(chunks)}
const webRequest=req=>new Request(origin+(req.url||'/'),{headers:{cookie:req.headers.cookie||'','cf-connecting-ip':req.socket.remoteAddress||'shared'}});
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.json':'application/json','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.woff2':'font/woff2'};
http.createServer(async(req,res)=>{try{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');const u=new URL(req.url,origin),url=u.pathname;if(url==='/health'){res.end('ok');return}if(!previewAuth(req)){res.writeHead(401,{'WWW-Authenticate':'Basic realm="tvU private preview", charset="UTF-8"','Cache-Control':'no-store'});res.end('사이트 접근 인증이 필요합니다.');return}
if(!['GET','HEAD'].includes(req.method)&&req.headers.origin!==origin)return json(res,{error:'요청 출처가 일치하지 않습니다.'},403);
const request=webRequest(req);
if(url==='/api/sysop/login'&&req.method==='POST'){const b=JSON.parse(await body(req,1024));if(typeof b.username!=='string'||typeof b.password!=='string'||b.password.length>128)return json(res,{error:'아이디와 비밀번호를 입력하세요.'},400);const r=await login(request,authStore,b.username,b.password);return r.token?json(res,{ok:true,initial:r.initial},200,{'Set-Cookie':cookie(r.token)}):json(res,{error:r.error},r.status)}
if(url==='/api/sysop/logout'&&req.method==='POST'){const s=await session(request,authStore);if(s)await authStore.delete('auth/sessions/'+s.id);return json(res,{ok:true},200,{'Set-Cookie':cookie('',0)})}
if(url==='/api/state'&&req.method==='GET')return json(res,await read('published.json'));
if(url==='/api/realmeter'&&req.method==='GET'){const {config}=await read('published.json'),out={period:'2026-07',sourceStatus:'관리자 발행 데이터 · 원문 직접 대조 전'};for(const key of ['general','relative','education','life']){const s=config.datasets.find(s=>s.id==='realmeter-'+key);out[key]=s?calculate(s).filter(r=>!r.some(c=>c.error)&&typeof r[2]?.value==='number').map(r=>[String(r[0].value),String(r[1].value),r[2].value]).sort((a,b)=>b[2]-a[2]):[]}return json(res,out)}
if(url==='/api/logo'&&req.method==='GET'){const key=u.searchParams.get('key')||'';if(!/^[a-f0-9-]+\.(png|jpg|webp)$/.test(key))return json(res,{error:'사진 없음'},404);try{const bytes=await fs.readFile(path.join(data,'logos',key));res.writeHead(200,{'Content-Type':mime[path.extname(key)],'Cache-Control':'public,max-age=31536000,immutable'});res.end(bytes);return}catch{return json(res,{error:'사진 없음'},404)}}
if(url.startsWith('/api/')){const s=await session(request,authStore);if(url==='/api/me')return json(res,{admin:!!s});if(!s)return json(res,{error:'관리자 로그인이 필요합니다.'},403);
if(url==='/api/sysop/password'&&req.method==='POST'){const b=JSON.parse(await body(req,1024));if(typeof b.current!=='string'||typeof b.next!=='string')return json(res,{error:'비밀번호를 입력하세요.'},400);const r=await changePassword(authStore,b.current,b.next);return r.status===200?json(res,{ok:true},200,{'Set-Cookie':cookie('',0)}):json(res,{error:r.error},r.status)}
if(url==='/api/draft'&&req.method==='GET'){let d=await read('draft.json');if(!d.etag)d={...(await read('published.json')),etag:null};return json(res,d)}
if(url==='/api/draft'&&req.method==='PUT'){const b=JSON.parse(await body(req,4000000));if(!('etag' in b))return json(res,{error:'버전 정보가 없습니다.'},400);return json(res,await serial(()=>write('draft.json',b.config,b.etag)))}
if(url==='/api/publish'&&req.method==='POST'){const b=JSON.parse(await body(req));return json(res,await serial(async()=>{const d=await read('draft.json'),p=await read('published.json');if(!d.etag||d.etag!==b.draftEtag||p.etag!==b.publishedEtag)throw Object.assign(Error('초안 또는 발행 버전이 바뀌었습니다.'),{status:409});if(p.etag)await atomic(path.join(data,'history',Date.now()+'-'+crypto.randomUUID()+'.json'),JSON.stringify(p.config));return write('published.json',d.config,b.publishedEtag)}))}
if((url==='/api/logo'||url==='/api/raw')&&req.method==='POST'){const bytes=await body(req,url==='/api/logo'?1100000:6000000),request=new Request(origin+url,{method:'POST',headers:{'Content-Type':req.headers['content-type']||''},body:bytes}),form=await request.formData(),f=form.get('file');if(!(f instanceof File))return json(res,{error:'파일을 선택하세요.'},400);if(url==='/api/logo'){if(!f.size||f.size>1000000)return json(res,{error:'PNG·JPEG·WEBP 이미지, 최대 1MB.'},400);const bytes=Buffer.from(await f.arrayBuffer());let ext;if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)ext='png';else if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)ext='jpg';else if(bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP')ext='webp';else return json(res,{error:'PNG·JPEG·WEBP 이미지 파일만 지원합니다.'},400);const key=crypto.randomUUID()+'.'+ext;await atomic(path.join(data,'logos',key),bytes);return json(res,{url:'/api/logo?key='+key})}if(f.size>5000000||!(/\.(csv|json|txt)$/i.test(f.name)))return json(res,{error:'5MB 이하 CSV·JSON·TXT만 지원합니다.'},400);const id=Date.now()+'-'+crypto.randomUUID();await atomic(path.join(data,'raw',id+'.bin'),Buffer.from(await f.arrayBuffer()));await atomic(path.join(data,'raw',id+'.json'),JSON.stringify({key:'raw/'+id,name:f.name,size:f.size,uploaded:new Date().toISOString()}));return json(res,{key:'raw/'+id})}
if(url==='/api/raw'&&req.method==='GET'){const key=u.searchParams.get('key');if(key){if(!/^raw\/[a-zA-Z0-9-]+$/.test(key))return json(res,{error:'잘못된 경로'},400);const info=JSON.parse(await fs.readFile(path.join(data,key+'.json'),'utf8'));res.writeHead(200,{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(info.name)});res.end(await fs.readFile(path.join(data,key+'.bin')));return}const names=(await fs.readdir(path.join(data,'raw'))).filter(x=>x.endsWith('.json')).sort().reverse();return json(res,{files:await Promise.all(names.slice(0,100).map(async n=>JSON.parse(await fs.readFile(path.join(data,'raw',n),'utf8')))),truncated:names.length>100})}
return json(res,{error:'지원하지 않는 API'},404)}
const base=path.join(root,'dist');let target=path.resolve(base,'.'+decodeURIComponent(url));if(target!==base&&!target.startsWith(base+path.sep))return json(res,{error:'잘못된 경로'},403);if(['/','/admin','/sysop'].includes(url))target=path.join(base,'index.html');let contents;try{contents=await fs.readFile(target)}catch{return json(res,{error:'파일 없음'},404)}res.writeHead(200,{'Content-Type':mime[path.extname(target)]||'application/octet-stream','Cache-Control':'no-store'});res.end(req.method==='HEAD'?undefined:contents);
}catch(e){json(res,{error:e.name==='ZodError'?'입력 데이터 형식을 확인해 주세요.':e.message||'서버 오류'},e.status||400)}}).listen(port,'0.0.0.0',()=>console.log('tvU server listening'));
