import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {ConfigSchema,defaults} from './model.bundle.mjs';
const root=path.dirname(fileURLToPath(import.meta.url)),data=path.resolve(process.env.DATA_DIR||path.join(root,'data')),port=Number(process.env.PORT||3000),origin=process.env.PUBLIC_ORIGIN||(process.env.RAILWAY_PUBLIC_DOMAIN?"https://"+process.env.RAILWAY_PUBLIC_DOMAIN:undefined),user=process.env.ADMIN_USER||'admin',pass=process.env.ADMIN_PASSWORD;
if(!origin||!pass||pass.length<16)throw new Error('PUBLIC_ORIGIN과 16자 이상의 ADMIN_PASSWORD 환경변수가 필요합니다.');
if(!origin.startsWith('https://')&&!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin))throw new Error('외부 서버는 HTTPS PUBLIC_ORIGIN이 필요합니다.');
await fs.mkdir(path.join(data,'raw'),{recursive:true});await fs.mkdir(path.join(data,'history'),{recursive:true});
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');const digest=v=>crypto.createHash('sha256').update(v).digest();const expected=digest(user+':'+pass);
const auth=req=>{const h=req.headers.authorization||'';return h.startsWith('Basic ')&&crypto.timingSafeEqual(digest(Buffer.from(h.slice(6),'base64').toString()),expected)};
async function read(name){try{const t=await fs.readFile(path.join(data,name),'utf8');return {config:JSON.parse(t),etag:hash(t),updated:(await fs.stat(path.join(data,name))).mtime.toISOString()}}catch(e){if(e.code==='ENOENT')return {config:defaults,etag:null,updated:null};throw e}}
async function write(name,config,etag){const cur=await read(name);if(cur.etag!==etag)throw Object.assign(new Error('다른 편집이 먼저 저장되었습니다. 다시 불러와 주세요.'),{status:409});const text=JSON.stringify(ConfigSchema.parse(config)),tmp=path.join(data,name+'.'+crypto.randomUUID()+'.tmp');await fs.writeFile(tmp,text,{mode:0o600});await fs.rename(tmp,path.join(data,name));return read(name)}
const json=(res,b,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(b))};let queue=Promise.resolve();function serial(fn){const x=queue.then(fn);queue=x.catch(()=>{});return x}
async function body(req,max=6_000_000){let size=0,chunks=[];for await(const c of req){size+=c.length;if(size>max)throw Object.assign(new Error('파일 크기 제한을 초과했습니다.'),{status:413});chunks.push(c)}return Buffer.concat(chunks)}
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.json':'application/json','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2'};
http.createServer(async(req,res)=>{try{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');if(req.url==='/health'){res.end('ok');return}if(!auth(req)){res.writeHead(401,{'WWW-Authenticate':'Basic realm="tvU private preview", charset="UTF-8"','Cache-Control':'no-store'});res.end('관리자 계정으로 로그인하세요.');return}const u=new URL(req.url,origin),url=u.pathname;
if(!['GET','HEAD'].includes(req.method)&&req.headers.origin!==origin)return json(res,{error:'요청 출처가 일치하지 않습니다.'},403);
if(url==='/api/me')return json(res,{admin:true});
if(url==='/api/state')return json(res,await read('published.json'));
if(url==='/api/draft'&&req.method==='GET'){let d=await read('draft.json');if(!d.etag)d={...(await read('published.json')),etag:null};return json(res,d)}
if(url==='/api/draft'&&req.method==='PUT'){const b=JSON.parse(await body(req,4_000_000));return json(res,await serial(()=>write('draft.json',b.config,b.etag)))}
if(url==='/api/publish'&&req.method==='POST'){const b=JSON.parse(await body(req));return json(res,await serial(async()=>{const d=await read('draft.json'),p=await read('published.json');if(!d.etag||d.etag!==b.draftEtag||p.etag!==b.publishedEtag)throw Object.assign(new Error('초안 또는 발행 버전이 바뀌었습니다.'),{status:409});if(p.etag)await fs.writeFile(path.join(data,'history',Date.now()+'-'+crypto.randomUUID()+'.json'),JSON.stringify(p.config),{mode:0o600});return write('published.json',d.config,b.publishedEtag)}))}
if(url==='/api/raw'&&req.method==='POST'){const bytes=await body(req);const request=new Request(origin+'/api/raw',{method:'POST',headers:{'Content-Type':req.headers['content-type']||''},body:bytes});const form=await request.formData();const f=form.get('file');if(!(f instanceof File)||f.size>5_000_000||!(/\.(csv|json|txt)$/i.test(f.name)))return json(res,{error:'5MB 이하 CSV·JSON·TXT만 지원합니다.'},400);const id=Date.now()+'-'+crypto.randomUUID();await fs.writeFile(path.join(data,'raw',id+'.bin'),Buffer.from(await f.arrayBuffer()),{mode:0o600});await fs.writeFile(path.join(data,'raw',id+'.json'),JSON.stringify({key:'raw/'+id,name:f.name,size:f.size,uploaded:new Date().toISOString()}),{mode:0o600});return json(res,{key:'raw/'+id})}
if(url==='/api/raw'&&req.method==='GET'){const key=u.searchParams.get('key');if(key){if(!/^raw\/[a-zA-Z0-9-]+$/.test(key))return json(res,{error:'잘못된 경로'},400);const info=JSON.parse(await fs.readFile(path.join(data,key+'.json'),'utf8'));res.writeHead(200,{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(info.name)});res.end(await fs.readFile(path.join(data,key+'.bin')));return}const names=(await fs.readdir(path.join(data,'raw'))).filter(x=>x.endsWith('.json')).sort().reverse();const files=await Promise.all(names.slice(0,100).map(n=>fs.readFile(path.join(data,'raw',n),'utf8').then(JSON.parse)));return json(res,{files,truncated:names.length>100})}
if(url.startsWith('/api/'))return json(res,{error:'지원하지 않는 API'},404);
const rel=decodeURIComponent(url),base=path.join(root,'dist');let target=path.resolve(base,'.'+rel);if(!target.startsWith(base+path.sep)&&target!==base)return json(res,{error:'허용하지 않는 경로'},403);if(url==='/'||url==='/admin')target=path.join(base,'index.html');let contents;try{contents=await fs.readFile(target)}catch{return json(res,{error:'파일 없음'},404)}res.writeHead(200,{'Content-Type':mime[path.extname(target)]||'application/octet-stream','Cache-Control':'no-store'});res.end(contents);
}catch(e){json(res,{error:e.name==='ZodError'?'입력 데이터 형식을 확인해 주세요.':e.message||'서버 오류'},e.status||400)}}).listen(port,'0.0.0.0',()=>console.log('tvU standalone server listening on '+port));
