const fs=require('node:fs'),assert=require('node:assert/strict'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,file)=>m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
const React=require('react'),{renderToStaticMarkup:render}=require('react-dom/server');
const {ConfigSchema,defaults}=require('../lib/model.ts'),{orderedIds,moveBlock}=require('../lib/home-layout.ts');
const old=require('../lib/railway-baseline.json');const c=ConfigSchema.parse(old);assert.equal(c.home.collapsed,false);assert.equal(c.home.animate,true);assert.equal(c.appearance.background,'#faf9fd');assert.equal(c.datasets.length,defaults.datasets.length);
assert.deepEqual(orderedIds(['a','b','c'],['c','c','missing']),['c','a','b']);assert.deepEqual(moveBlock(['a','b','c'],'a','c'),['b','c','a']);assert.deepEqual(moveBlock(['a','b','c'],'c','a'),['c','a','b']);assert.deepEqual(moveBlock(['a','b'],'missing','b'),['a','b']);
assert.equal(ConfigSchema.safeParse({...c,appearance:{...c.appearance,logo:'javascript:alert(1)'}}).success,false);assert.equal(ConfigSchema.safeParse({...c,appearance:{...c.appearance,accent:'red; color:black'}}).success,false);
const {HomeBlocks}=require('../src/home-blocks.tsx');const props={blocks:[{id:'a',title:'자료 제목',content:React.createElement('p',null,'값 12')}],order:[]};let html=render(React.createElement(HomeBlocks,props));assert.match(html,/자료 제목/);assert.match(html,/<details[^>]* open/);html=render(React.createElement(HomeBlocks,{...props,editing:true,onOrder:()=>{}}));assert.match(html,/<details[^>]* open/);assert.match(html,/draggable="true"/);assert.match(html,/이 박스 편집/);
const {SheetView,views}=require('../src/dataset-view.tsx');for(const [view] of views.filter(([id])=>['table','striped','ranking','comparison','cards','bar'].includes(id))){const h=render(React.createElement(SheetView,{sheet:{...c.datasets[0],view},onCellSelect:()=>{}}));assert.match(h,/sheet-animated/);assert.match(h,/preview-cell/);assert.match(h,/광주/)}
const DataStudio=require('../src/admin/data-studio.tsx').default;html=render(React.createElement(DataStudio,{sheets:c.datasets,onChange:()=>{},selectedId:'realmeter-general'}));assert.match(html,/실시간 미리보기/);assert.match(html,/이철우/);assert.match(html,/table-studio-preview/);
const Dashboard=require('../src/dashboard.tsx').default;html=render(React.createElement(Dashboard,{initialConfig:c,embedded:true}));assert.match(html,/home-blocks/);assert.match(html,/<details class="home-disclosure" open/);assert.match(html,/--accent:#9272c8/);
console.log('기존 설정 호환·박스 순서·기본 접힘·드래그 편집·6종 표 미리보기·브랜드 입력 검증 통과');

const {blockSetting}=require('../lib/home-settings.ts');assert.equal(blockSetting('ask',{}).collapsed,false);assert.equal(blockSetting('map',{}).collapsed,false);assert.equal(blockSetting('watch',{}).collapsed,false);assert.equal(blockSetting('ranking',{}).collapsed,false);assert.equal(blockSetting('dataset:recycling',{}).collapsed,false);assert.equal(blockSetting('dataset:realmeter-general',{}).collapsed,false);
function opening(h,id){const start=h.indexOf('data-block-id="'+id+'"');assert.ok(start>=0,id);const m=h.slice(start).match(/<details[^>]*>/);assert.ok(m,id);return m[0]}
for(const id of ['ask','map','watch','ranking','monthly'])assert.match(opening(html,id),/open=""/);for(const id of ['dataset:recycling','dataset:realmeter-general','dataset:realmeter-relative','dataset:realmeter-education','dataset:realmeter-life'])assert.match(opening(html,id),/open=""/);assert.match(html,/월간 주요 데이터/);assert.match(html,/home-ranking-banner/);
const highlighted={...c,home:{...c.home,settings:{ask:{collapsed:true,highlight:true}}}};html=render(React.createElement(Dashboard,{initialConfig:highlighted,embedded:true}));assert.doesNotMatch(opening(html,'ask'),/open=""/);assert.match(html,/title-crown/);assert.match(html,/aria-label="강조"/);assert.equal(ConfigSchema.parse(highlighted).home.settings.ask.highlight,true);
console.log('월간 자료만 기본 접힘·질문/지도/눈여겨볼 데이터 펼침·오른쪽 배너·항목별 설정·왕관 강조 검증 통과');
