'use client';
import {useEffect,useState} from 'react';
import {ConfigSchema,defaults,metricNames,type Config} from '../../lib/model';
import SubscriptionStudio from './subscription-studio';
import SysopLogin from './sysop-login';
import PasswordStudio from './password-studio';
import LeaderStudio from './leader-studio';
import RankingStudio from './ranking-studio';
import LayoutStudio from './layout-studio';
import MapStudio from './map-studio';
import AppearanceStudio from './appearance-studio';
import DataStudio from './data-studio';
import {Avatar} from '../dashboard';
const tabs=[['homepage','홈페이지 관리'],['content','문구·기사'],['layout','레이아웃·접기·강조'],['appearance','색상·로고'],['mapstyle','지도 색상·효과'],['data','데이터 수치'],['tables','수치·수식·표'],['leaders','전국 단체장 자료'],['ranking','자동 종합순위'],['sources','정부 API 출처'],['raw','원본 파일'],['subscription','프리미엄 구독'],['password','비밀번호 변경']] as const;
const uid=()=>crypto.randomUUID();
function download(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csvRows(s:string){const out:string[][]=[];let row:string[]=[],cell='',quote=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(quote&&s[i+1]==='"'){cell+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&s[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))out.push(row);row=[];cell=''}else cell+=c}if(quote)throw new Error('CSV 따옴표가 닫히지 않았습니다.');row.push(cell);if(row.some(Boolean))out.push(row);return out}
export default function Admin(){const [admin,setAdmin]=useState<boolean|null>(null),[cfg,setCfg]=useState<Config>(defaults),[tab,setTab]=useState('homepage'),[etag,setEtag]=useState<string|null>(null),[publishedEtag,setPublishedEtag]=useState<string|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[regions,setRegions]=useState<{id:string;name:string;parent:string}[]>([]),[files,setFiles]=useState<any[]>([]),[leaderIndex,setLeaderIndex]=useState(0),[regionFilter,setRegionFilter]=useState(''),[sourceIndex,setSourceIndex]=useState(0);
async function request(url:string,options?:RequestInit){const r=await fetch(url,options);const b:any=await r.json();if(!r.ok)throw new Error(b.error||'요청을 처리하지 못했습니다.');return b}
async function load(){setBusy(true);setError('');try{const [d,p]=await Promise.all([request('/api/draft'),request('/api/state')]);setCfg(ConfigSchema.parse(d.config));setEtag(d.etag);setPublishedEtag(p.etag);setDirty(false);setMessage('서버에 저장된 초안을 불러왔습니다.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function loadFiles(){try{const b=await request('/api/raw');setFiles(b.files);if(b.truncated)setMessage('파일 목록은 최대 100개를 표시합니다.')}catch(e){setError((e as Error).message)}}
useEffect(()=>{const h=()=>{const t=location.hash.slice(1);if(tabs.some(a=>a[0]===t))setTab(t)};h();window.addEventListener('hashchange',h);request('/api/me').then(b=>{setAdmin(b.admin);if(b.admin){load();loadFiles()}}).catch(()=>{setAdmin(false);setError('로그인 상태 확인 실패')});fetch('/maps/boundaries.json').then(r=>r.json()).then((d:any)=>setRegions([{id:'KR',name:'대한민국',parent:''},...d.regions])).catch(()=>setError('지역 코드 목록을 불러오지 못했습니다.'));return()=>window.removeEventListener('hashchange',h)},[]);
useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
function edit(next:Config){setCfg(next);setDirty(true);setMessage('변경사항이 있습니다. 초안 저장 후 발행해 주세요.');setError('')}
function validate(){const parsed=ConfigSchema.safeParse(cfg);if(!parsed.success)throw new Error(parsed.error.issues.map(x=>x.message).join('; '));const allowed=new Set(regions.map(r=>r.id));if(regions.length&&cfg.records.some(r=>!allowed.has(r.regionId)))throw new Error('지도 목록에 없는 지역코드가 있습니다.');return parsed.data}
async function save(){setBusy(true);setError('');try{const config=validate();const b=await request('/api/draft',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({config,etag})});setEtag(b.etag);setCfg(b.config);setDirty(false);setMessage('초안이 서버에 저장되었습니다. 미리보기 후 발행할 수 있습니다.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function publish(){setBusy(true);setError('');try{const b=await request('/api/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({draftEtag:etag,publishedEtag})});setPublishedEtag(b.etag);setMessage('발행 완료. 사이트를 새로 열면 변경된 내용이 반영됩니다.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function mainEdit(){if(dirty){setBusy(true);try{const config=validate();await request('/api/draft',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({config,etag})});setDirty(false);location.assign('/?edit=1')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}else location.assign('/?edit=1')}
function recordChange(id:string,key:string,value:any){edit({...cfg,records:cfg.records.map(r=>r.id===id?{...r,[key]:value}:r)})}
async function importRecords(file?:File){if(!file)return;setError('');try{let records:any[];const raw=await file.text();if(file.name.toLowerCase().endsWith('.csv')){const rows=csvRows(raw.replace(/^\uFEFF/,''));const header=rows.shift()||[];const needed=['regionId','metric','value','year','source','status','note'];if(!needed.every(k=>header.includes(k)))throw new Error('CSV 열 이름이 템플릿과 다릅니다.');records=rows.map(row=>{const a=Object.fromEntries(header.map((k,i)=>[k,row[i]??'']));if(!a.value.trim()||!a.year.trim()||!a.metric.trim())throw new Error('수치·연도·지표가 비어 있는 행이 있습니다.');return {id:uid(),regionId:a.regionId,metric:Number(a.metric),value:Number(a.value),year:Number(a.year),source:a.source,status:a.status||'reference',note:a.note}})}else{const b=JSON.parse(raw);records=Array.isArray(b)?b:b.records;if(!Array.isArray(records))throw new Error('JSON 배열 또는 records 배열이 필요합니다.');records=records.map(r=>({...r,id:r.id||uid()}))}const merged={...cfg,records:[...cfg.records,...records]};const result=ConfigSchema.safeParse(merged);if(!result.success)throw new Error(result.error.issues.map(x=>x.message).join('; '));const ids=new Set(regions.map(r=>r.id));if(regions.length&&records.some(r=>!ids.has(r.regionId)))throw new Error('지도 목록에 없는 지역코드입니다. 코드표를 확인해 주세요.');edit(result.data);setMessage(records.length+'개 행을 편집 초안에 추가했습니다. 검수 후 저장해 주세요.')}catch(e){setError((e as Error).message)}}
async function upload(file?:File){if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);await request('/api/raw',{method:'POST',body:form});await loadFiles();setMessage('원본 파일을 서버에 보관했습니다. 수치 반영은 데이터 수치 메뉴에서 별도로 진행하세요.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
const regionOptions=regions.map(r=><option key={r.id} value={r.id}>{r.name} · {r.id}</option>);const l=cfg.leaders[leaderIndex],source=cfg.sources[sourceIndex];
if(admin===null)return <div className="login-panel"><h2>관리자 권한 확인 중…</h2></div>;
if(!admin)return <SysopLogin onLogin={()=>{setAdmin(true);load();loadFiles()}}/>;
return <div className="admin-app"><header className="topbar"><a href="/" className="brand"><span className="brand-icon">L</span><span>지방정부 tvU 데이터랩<small>CONTENT & DATA STUDIO</small></span></a><nav><button onClick={async()=>{await request('/api/sysop/logout',{method:'POST'});setAdmin(false);setCfg(defaults);setDirty(false)}}>로그아웃</button><a href="/" target="_blank">발행 화면 ↗</a><a href="/?preview=1" target="_blank">저장된 초안 미리보기 ↗</a></nav></header><div className="admin-shell"><aside className="admin-sidebar"><span className="section-label">관리자 페이지</span><h2>편집 스튜디오</h2><details className="admin-home-group" open><summary>홈페이지 관리</summary>{tabs.filter(([id])=>['homepage','layout','content','appearance','mapstyle','subscription'].includes(id)).map(([id,title])=><a className={tab===id?'selected':''} href={'#'+id} key={id}>{title}<span>→</span></a>)}</details>{tabs.filter(([id])=>!['homepage','layout','content','appearance','mapstyle','subscription'].includes(id)).map(([id,title])=><a className={tab===id?'selected':''} href={'#'+id} key={id}>{title}<span>→</span></a>)}<div className="admin-help">① 편집<br/>② 초안 저장<br/>③ 미리보기<br/>④ 사이트에 발행<p>초안과 발행본을 별도로 보관합니다. 다른 사람이 먼저 저장한 경우 덮어쓰지 않습니다.</p></div><a href="/legacy.html#operation" target="_blank">기존 구축·운영안 ↗</a></aside><main className="admin-main"><div className="admin-toolbar"><div><span className="section-label">WORKSPACE / EDITOR</span><h1>{tabs.find(t=>t[0]===tab)?.[1]}</h1></div><div className="actions"><button disabled={busy} onClick={()=>{if(!dirty||confirm('저장하지 않은 편집을 버리고 다시 불러올까요?'))load()}}>다시 불러오기</button><button className="primary" disabled={busy} onClick={save}>{busy?'처리 중…':'초안 저장'}</button><button className="publish" disabled={busy||dirty||!etag} onClick={publish}>사이트에 발행</button></div></div><div className="editor-status" role="status">{dirty?'● 저장 전 변경사항':'✓ 서버 초안 기준'}{message&&' · '+message}</div>{error&&<div className="error" role="alert">{error}</div>}
{tab==='subscription'&&<SubscriptionStudio config={cfg} onChange={edit}/>}{tab==='password'&&<PasswordStudio/>}{tab==='tables'&&<DataStudio sheets={cfg.datasets} onChange={datasets=>edit({...cfg,datasets})}/>}
{tab==='homepage'&&<section className="panel form-panel"><h2>홈페이지 통합 관리</h2><p>메인 화면에서 제목·설명·표를 직접 편집합니다. 세부 설정은 아래 분야를 선택하세요.</p><button className="primary" disabled={busy} onClick={mainEdit}>메인 편집 · 발행 화면으로 이동</button><div className="homepage-management-grid">{tabs.filter(([id])=>['layout','content','appearance','mapstyle','subscription'].includes(id)).map(([id,title])=><a className="panel" href={'#'+id} key={id}><b>{title}</b><span>설정 열기 →</span></a>)}</div><p className="muted">메인 편집의 완료 버튼은 저장과 발행을 함께 처리합니다. 사진은 단체장 자료 메뉴의 등록 정보를 사용합니다.</p></section>}
{tab==='content'&&<><section className="panel form-panel"><h2>메인 화면 문구</h2><div className="form-grid">{([['title','메인 제목'],['subtitle','설명 문구'],['notice','상단 안내문'],['rankingTitle','순위 영역 제목'],['footer','하단 기관명'],['askTitle','데이터에 질문하기 제목']] as const).map(([key,label])=><label key={key}>{label}<input value={cfg.content[key]} onChange={e=>edit({...cfg,content:{...cfg.content,[key]:e.target.value}})}/></label>)}<label>질문 제목 정렬<select value={cfg.content.askAlign} onChange={e=>edit({...cfg,content:{...cfg.content,askAlign:e.target.value as any}})}><option value="left">왼쪽</option><option value="center">가운데</option><option value="right">오른쪽</option></select></label></div></section><section className="panel form-panel"><div className="row-title"><h2>기획 기사 카드</h2><button onClick={()=>edit({...cfg,stories:[...cfg.stories,{id:uid(),title:'새 기획 제목',body:'내용을 입력하세요.'}]})}>＋ 카드 추가</button></div>{cfg.stories.map((s,i)=><div className="edit-card" key={s.id}><label>제목<input value={s.title} onChange={e=>edit({...cfg,stories:cfg.stories.map(x=>x.id===s.id?{...x,title:e.target.value}:x)})}/></label><label>본문<textarea value={s.body} onChange={e=>edit({...cfg,stories:cfg.stories.map(x=>x.id===s.id?{...x,body:e.target.value}:x)})}/></label><div className="actions"><button disabled={i===0} onClick={()=>{const a=[...cfg.stories];[a[i-1],a[i]]=[a[i],a[i-1]];edit({...cfg,stories:a})}}>위로</button><button className="danger" onClick={()=>edit({...cfg,stories:cfg.stories.filter(x=>x.id!==s.id)})}>카드 삭제</button></div></div>)}</section></>}
{tab==='layout'&&<LayoutStudio config={cfg} onChange={edit} onMainEdit={mainEdit} onSave={save} onPublish={publish} busy={busy} canPublish={!dirty&&!!etag} status={message} error={error}/>}
{tab==='mapstyle'&&<MapStudio config={cfg} onChange={edit}/>}{tab==='appearance'&&<AppearanceStudio config={cfg} onChange={edit}/>}
{tab==='data'&&<section className="panel form-panel"><div className="row-title"><h2>지역별 원수치 입력</h2><button onClick={()=>edit({...cfg,records:[...cfg.records,{id:uid(),regionId:regionFilter||'KR',metric:0,value:0,year:2026,source:'',status:'reference',note:''}]})}>＋ 수치 행 추가</button></div><div className="callout">같은 지역·지표·연도는 한 행만 저장합니다. 청렴도는 1~5등급이며, 미입력 값은 행을 만들지 않습니다. 종합순위 점수는 별도 시연값입니다.</div><div className="actions wrap"><select aria-label="지역별 수치 필터" value={regionFilter} onChange={e=>setRegionFilter(e.target.value)}><option value="">모든 지역</option>{regionOptions}</select><button onClick={()=>download('지표입력_템플릿.csv','\ufeffregionId,metric,value,year,source,status,note\nKR,0,50,2025,,demo,예시 행 삭제 후 입력','text/csv;charset=utf-8')}>CSV 템플릿</button><label className="file-button">CSV·JSON 가져오기<input type="file" accept=".csv,.json" onChange={e=>{importRecords(e.target.files?.[0]);e.target.value=''}}/></label><button onClick={()=>download('지역코드.json',JSON.stringify(regions,null,2))}>지역 코드표</button></div><p className="tiny muted">metric: 0 재정자립도 / 1 재정자주도 / 2 통합재정수지 / 3 채무 / 4 종합청렴도 / 5 청렴체감도. status: demo, reference, verified. CSV 가져오기는 기존 행에 추가하며 중복은 거부합니다.</p>{cfg.records.filter(r=>!regionFilter||r.regionId===regionFilter).map(r=><div className="edit-card data-edit" key={r.id}><label>지역<select value={r.regionId} onChange={e=>recordChange(r.id,'regionId',e.target.value)}>{regionOptions}</select></label><label>지표<select value={r.metric} onChange={e=>recordChange(r.id,'metric',Number(e.target.value))}>{metricNames.map((m,i)=><option value={i} key={m}>{m}</option>)}</select></label><label>원수치<input type="number" step="any" value={r.value} onChange={e=>recordChange(r.id,'value',e.target.value===''?NaN:Number(e.target.value))}/></label><label>기준연도<input type="number" value={r.year} onChange={e=>recordChange(r.id,'year',Number(e.target.value))}/></label><label>검수 상태<select value={r.status} onChange={e=>recordChange(r.id,'status',e.target.value)}><option value="reference">원기관 대조 전</option><option value="verified">검수 완료</option><option value="demo">시연 자료</option></select></label><label>원문 URL<input value={r.source} onChange={e=>recordChange(r.id,'source',e.target.value)} placeholder="https://"/></label><label className="wide">비고<input value={r.note} onChange={e=>recordChange(r.id,'note',e.target.value)}/></label><button className="danger" onClick={()=>edit({...cfg,records:cfg.records.filter(x=>x.id!==r.id)})}>행 삭제</button></div>)}</section>}
{tab==='leaders'&&<LeaderStudio config={cfg} onChange={edit}/>}
{tab==='ranking'&&<RankingStudio config={cfg} onChange={edit}/>}
{tab==='sources'&&<section className="panel form-panel"><div className="row-title"><h2>정부 데이터 API 연결 준비</h2><button onClick={()=>{edit({...cfg,sources:[...cfg.sources,{id:uid(),name:'새 출처',url:'',keyName:'',cycle:'',mapping:''}]});setSourceIndex(cfg.sources.length)}}>＋ 출처 추가</button></div><div className="callout">현재는 출처·API 주소·갱신주기·필드 매핑을 저장합니다. 자동 호출·예약 수집은 아직 연결하지 않았습니다. 인증키 값은 이 화면에 입력하지 말고 서버 비밀 설정에 보관해야 합니다.</div><select aria-label="출처 선택" value={sourceIndex} onChange={e=>setSourceIndex(Number(e.target.value))}>{cfg.sources.map((s,i)=><option key={s.id} value={i}>{s.name}</option>)}</select>{source&&<><div className="form-grid">{([['name','출처 이름'],['url','API 또는 원기관 HTTPS 주소'],['keyName','서버 비밀변수 이름 · 키 값 입력 금지'],['cycle','갱신 주기']] as const).map(([key,label])=><label key={key}>{label}<input value={source[key]} onChange={e=>edit({...cfg,sources:cfg.sources.map((x,i)=>i===sourceIndex?{...x,[key]:e.target.value}:x)})}/></label>)}</div><label>필드 매핑·통계표 ID·운영 메모<textarea rows={6} value={source.mapping} onChange={e=>edit({...cfg,sources:cfg.sources.map((x,i)=>i===sourceIndex?{...x,mapping:e.target.value}:x)})}/></label><button className="danger" onClick={()=>{edit({...cfg,sources:cfg.sources.filter((_,i)=>i!==sourceIndex)});setSourceIndex(0)}}>출처 삭제</button></>}</section>}
{tab==='raw'&&<><section className="panel form-panel"><h2>원본 파일 보관</h2><p className="muted">CSV·JSON·TXT, 파일당 최대 5MB. 원본을 서버에 보관하며 지표를 자동 변경하지 않습니다.</p><label className="file-button primary">원본 업로드<input type="file" accept=".csv,.json,.txt" disabled={busy} onChange={e=>{upload(e.target.files?.[0]);e.target.value=''}}/></label><button onClick={loadFiles}>목록 새로고침</button><div className="table-scroll"><table><thead><tr><th>파일명</th><th>크기</th><th>보관 시각</th></tr></thead><tbody>{files.map(f=><tr key={f.key}><td><a href={'/api/raw?key='+encodeURIComponent(f.key)}>{f.name} ↓</a></td><td>{(f.size/1024).toFixed(1)} KB</td><td>{new Date(f.uploaded).toLocaleString('ko-KR')}</td></tr>)}</tbody></table></div>{!files.length&&<p className="muted">아직 보관한 원본이 없습니다.</p>}</section><section className="panel form-panel"><h2>편집 설정 내보내기·불러오기</h2><p className="muted">문구·레이아웃·프로필·지표·출처를 JSON 파일로 내보냅니다. 가져오기는 현재 편집 초안을 교체하며 저장 전까지 서버에는 반영되지 않습니다.</p><button onClick={()=>download('지방정부_편집설정.json',JSON.stringify(cfg,null,2))}>전체 설정 내려받기</button><label className="file-button">전체 설정 가져오기<input type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{const next=ConfigSchema.parse(JSON.parse(await f.text()));if(confirm('현재 편집 초안을 파일 내용으로 교체할까요?')){edit(next);setLeaderIndex(0);setSourceIndex(0)}}catch{setError('설정 형식이 올바르지 않습니다. 이 관리자에서 내보낸 JSON을 사용하세요.')}}}/></label></section></>}
</main></div></div>}
