'use client';
import {useState} from 'react';
import type {Config} from '../../lib/model';
import regions from '../../lib/regions.json';
import {parties} from '../../lib/parties';
import {Avatar} from '../dashboard';
export const provinceOf=(id:string):string=>{const r=regions.find(r=>r.id===id);return !r?'':r.parent==='KR'?r.id:provinceOf(r.parent)};
export function filterLeaders(leaders:Config['leaders'],query:string,province:string,kind:string){return leaders.filter(l=>(l.name+l.role+l.dataKey).includes(query)&&(!province||provinceOf(l.regionId)===province)&&(!kind||(kind==='metro'?l.level==='metro':l.level==='basic'&&l.role.endsWith(kind))))}
export default function LeaderStudio({config,onChange}:{config:Config;onChange:(c:Config)=>void}){
 const [category,setCategory]=useState('');const [query,setQuery]=useState(''),[selected,setSelected]=useState(''),[province,setProvince]=useState(''),[kind,setKind]=useState(''),[uploadStatus,setUploadStatus]=useState('');
 const list=filterLeaders(config.leaders,query,province,kind),l=config.leaders.find(l=>l.id===selected);
 const edit=(patch:Partial<Config['leaders'][number]>)=>onChange({...config,leaders:config.leaders.map(x=>x.id===l?.id?{...x,...patch}:x)});
 const chooseProvince=(id:string)=>edit({regionId:id,level:'metro'});
 return <section className="panel form-panel"><h2>단체장 자료·사진·정당·경력·공약</h2><p>상위 시·도와 시·군·구별로 자료를 찾아 편집하세요. 사진·소속정당·경력·공약을 수정하면 아래 미리보기와 관리자 초안에 바로 반영됩니다. 저장·발행하면 정책지도와 프로필에도 연동됩니다.</p><p className="tiny muted">미확인 정당은 추정하지 않습니다. 지도는 2023년 경계이므로 신규 행정구역은 최신 지도 코드가 확보될 때까지 미연결로 관리해 주세요.</p>
 <div className="region-chips hierarchy-tabs">{['도','시','군','구'].map(t=><button key={t} className={category===t?'primary':''} onClick={()=>{setCategory(t);setProvince('');setSelected('');setKind(t==='도'?'metro':t==='시'?'시장':t==='군'?'군수':'구청장')}}>{t}</button>)}</div>
 {category&&<><h3>상위 시·도 선택</h3><div className="region-chips">{regions.filter(r=>r.parent==='KR'&&(category!=='도'||r.name.endsWith('도'))).map(r=>{const entries=filterLeaders(config.leaders,'',r.id,kind),done=entries.length>0&&entries.every(x=>x.name&&x.photo&&x.career&&x.policies&&x.pledges);return <button key={r.id} className={'region-entry '+(done?'complete':'incomplete')+(province===r.id?' selected':'')} onClick={()=>{setProvince(r.id);setSelected('')}}>{r.name}<small>{done?'기입 완료':'미기입'}</small></button>})}</div></>}
 {category&&province&&<><h3>미등록 하위 지역</h3><div className="region-chips">{regions.filter(r=>provinceOf(r.id)===province&&r.parent===province&&!config.leaders.some(l=>l.regionId===r.id)&&r.parent!=='KR'&&r.name.endsWith(category==='시'?'시':category==='군'?'군':category==='구'?'구':'도')).map(r=><button key={r.id} className="region-entry incomplete" onClick={()=>{const n={id:crypto.randomUUID(),name:'',party:'미확인',role:r.name+(category==='시'?'장':category==='군'?'수':'청장'),regionId:r.id,photo:'',career:'',source:'',level:'basic' as const,dataKey:r.name,asOf:'2026-07',historicalStatus:'pending' as const,policies:'',pledges:'',policySource:'',pledgeSource:'',photoSource:'',collectedAt:'',score:0,change:0};onChange({...config,leaders:[...config.leaders,n]});setSelected(n.id)}}>{r.name}<small>미기입 · 입력하기</small></button>)}</div></>}
 {category&&province&&<><h3>하위 지역 · 편집할 단체장</h3><div className="region-chips">{list.map(x=><button key={x.id} className={'region-entry '+(x.name&&x.photo&&x.career&&x.policies&&x.pledges?'complete':'incomplete')} onClick={()=>setSelected(x.id)}>{x.role} · {x.name}<small>{x.name&&x.photo&&x.career&&x.policies&&x.pledges?'기입 완료':'미기입'}</small></button>)}</div></>}
 <details><summary>검색·단체장 추가·세부 필터</summary>
 <div className="actions"><input placeholder="이름·지역 검색" aria-label="단체장 검색" value={query} onChange={e=>{setQuery(e.target.value);setSelected('')}}/><button onClick={()=>{const n={id:crypto.randomUUID(),name:'새 단체장',party:'미확인',role:'직위 입력',regionId:'',photo:'',career:'',source:'',level:'basic' as const,dataKey:'',asOf:'2026-07',historicalStatus:'pending' as const,policies:'',pledges:'',policySource:'',pledgeSource:'',photoSource:'',collectedAt:'',score:0,change:0};onChange({...config,leaders:[...config.leaders,n]});setSelected(n.id);setQuery('');setProvince('');setKind('')}}>＋ 단체장 추가</button></div>
 <div className="form-grid"><label>리스트 · 상위 시·도<select value={province} onChange={e=>{setProvince(e.target.value);setSelected('')}}><option value="">전국 전체</option>{regions.filter(r=>r.parent==='KR').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>리스트 · 행정구역 구분<select value={kind} onChange={e=>{setKind(e.target.value);setSelected('')}}><option value="">전체</option><option value="metro">광역 시·도</option><option value="시장">시 · 시장</option><option value="군수">군 · 군수</option><option value="구청장">구 · 구청장</option></select></label></div>
 <p className="tiny">검색 결과 {list.length}명</p><label>편집할 단체장<select value={l?.id||''} onChange={e=>setSelected(e.target.value)}><option value="">지역·단체장을 선택하세요</option>{[...list,...(l&&!list.some(x=>x.id===l.id)?[l]:[])].map(x=><option key={x.id} value={x.id}>{x.role} · {x.name} · {x.party}</option>)}</select></label></details>
 {l?<><div className="leader-preview"><Avatar src={l.photo} name={l.name} party={l.party}/><b>{l.name}</b><span>{l.role} · {l.party}</span></div><div className="form-grid">
 <label>소속정당 · 사진 테두리<select value={l.party} onChange={e=>edit({party:e.target.value})}>{[...parties,...(parties.includes(l.party as any)?[]:[l.party])].map(p=><option key={p} value={p}>{p}</option>)}</select></label>
 <label>지도 연결 · 상위 시·도<select value={provinceOf(l.regionId)} onChange={e=>chooseProvince(e.target.value)}><option value="">지역 미연결</option>{regions.filter(r=>r.parent==='KR').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
 <label>지도 연결 · 시·군·구<select value={l.regionId} onChange={e=>edit({regionId:e.target.value,level:e.target.value===provinceOf(l.regionId)?'metro':'basic'})}><option value="">지역 미연결</option>{regions.filter(r=>provinceOf(l.regionId)&&provinceOf(r.id)===provinceOf(l.regionId)).map(r=><option key={r.id} value={r.id}>{r.name} · {r.id}</option>)}</select></label>
 {([['name','이름'],['role','직위'],['regionId','지도 지역코드 · 직접 입력'],['dataKey','순위 표 연결키'],['asOf','재직 기준 시점'],['collectedAt','자료 확인일'],['photo','사진 HTTPS URL'],['photoSource','사진 출처'],['source','경력·재직 출처 URL'],['policySource','정책 출처 URL'],['pledgeSource','공약 출처 URL']] as const).map(([k,title])=><label key={k}>{title}<input value={l[k]} onChange={e=>edit({[k]:e.target.value})}/></label>)}
 <label>단체장 범위<select value={l.level} onChange={e=>edit({level:e.target.value as any})}><option value="basic">시장·군수·구청장</option><option value="metro">광역단체장</option></select></label><label>7월 재직 확인<select value={l.historicalStatus} onChange={e=>edit({historicalStatus:e.target.value as any})}><option value="pending">확인 필요</option><option value="confirmed">확인 완료</option></select></label></div>
 <label>프로필 사진 업로드 · PNG/JPEG/WEBP, 최대 1MB<input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploadStatus('업로드 중…');try{const form=new FormData();form.set('file',file);const response=await fetch('/api/logo',{method:'POST',body:form}),data=await response.json() as {url:string;error?:string};if(!response.ok)throw Error(data.error||'업로드 실패');edit({photo:data.url});setUploadStatus('사진을 업로드했습니다. 저장·발행하면 메인에 반영됩니다.')}catch(error){setUploadStatus(error instanceof Error?error.message:'업로드 실패')}e.target.value=''}}/></label><p aria-live="polite">{uploadStatus}</p><p className="tiny">테두리: 국민의힘 빨강 · 더불어민주당 파랑 · 개혁신당 주황 · 조국혁신당 진청/하늘 그라데이션 · 무소속 흰색</p>
 {([['career','주요 경력 · 한 줄에 하나'],['policies','주요 정책'],['pledges','공약 사항']] as const).map(([k,title])=><label key={k}>{title}<textarea rows={5} value={l[k]} onChange={e=>edit({[k]:e.target.value})}/></label>)}
 <p className="callout">종합점수는 ‘자동 종합순위’에 연결한 데이터로 계산합니다.</p><button className="danger" onClick={()=>{if(confirm('이 프로필을 삭제할까요?')){onChange({...config,leaders:config.leaders.filter(x=>x.id!==l.id)});setSelected('')}}}>프로필 삭제</button></>:<p>도·시·군·구 → 상위 지역 → 단체장을 선택하면 편집란이 열립니다.</p>}</section>
}
